// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listArtifactsForSession = `-- name: ListArtifactsForSession :many

SELECT id, session_id, type, url, metadata, created_at FROM artifacts
WHERE session_id = $1
ORDER BY created_at ASC
`

// Queries backing ArtifactStore (§4.3, §6.3 GET /api/sessions/:id/
// artifacts and the client WS hub's own SubscribedPayload.artifacts,
// §6.2). ListForSession only -- nothing in the codebase mints an artifact
// row yet (real artifact CREATION is a later Step: PR creation is Step
// 21+, previews Step 48, uploads Step 49), so no Create query exists here
// either.
func (q *Queries) ListArtifactsForSession(ctx context.Context, sessionID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Url,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
