// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automationinvocations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAutomationInvocationForFanOut = `-- name: ClaimAutomationInvocationForFanOut :one
UPDATE automation_invocations
SET fanned_out_at = now()
WHERE id = $1 AND fanned_out_at IS NULL
RETURNING id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at
`

// The CAS half of the claim-batch pair immediately above -- "UPDATE ...
// WHERE fanned_out_at IS NULL" guards against a crash-and-retry
// double-fanning-out the SAME invocation (see this table's own migration
// doc comment).
func (q *Queries) ClaimAutomationInvocationForFanOut(ctx context.Context, id pgtype.UUID) (AutomationInvocation, error) {
	row := q.db.QueryRow(ctx, claimAutomationInvocationForFanOut, id)
	var i AutomationInvocation
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Status,
		&i.Targets,
		&i.TotalRuns,
		&i.FannedOutAt,
		&i.FailureCountedAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const closeAutomationInvocation = `-- name: CloseAutomationInvocation :one
UPDATE automation_invocations
SET status = $2,
    closed_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at
`

type CloseAutomationInvocationParams struct {
	ID     pgtype.UUID                `json:"id"`
	Status AutomationInvocationStatus `json:"status"`
}

// Applies internal/domain/automation.InvocationTransition's own verdict --
// guarded by "AND status = 'pending'" so this invocation's own outcome is
// decided at most once, no matter how many concurrent callers (this
// Step's reconcile pump, the recovery sweep, or -- in principle -- both,
// racing on the SAME invocation's last remaining run) observe "every run
// is now terminal" at roughly the same time; exactly one of them ever
// wins this UPDATE (returns pgx.ErrNoRows to every loser, app/automation's
// own closeout.go).
func (q *Queries) CloseAutomationInvocation(ctx context.Context, arg CloseAutomationInvocationParams) (AutomationInvocation, error) {
	row := q.db.QueryRow(ctx, closeAutomationInvocation, arg.ID, arg.Status)
	var i AutomationInvocation
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Status,
		&i.Targets,
		&i.TotalRuns,
		&i.FannedOutAt,
		&i.FailureCountedAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAutomationInvocation = `-- name: CreateAutomationInvocation :one

INSERT INTO automation_invocations (automation_id, targets, total_runs)
VALUES ($1, $2, $3)
RETURNING id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at
`

type CreateAutomationInvocationParams struct {
	AutomationID pgtype.UUID `json:"automation_id"`
	Targets      []byte      `json:"targets"`
	TotalRuns    int32       `json:"total_runs"`
}

// Queries backing AutomationInvocationStore (Step 51, "automations:
// engine", §3.5), migrations/000052_automation_invocations.up.sql.
// Fast, cheap, durable hand-off (mirrors internal/app/releasereview.
// Enqueue's own identical "one INSERT, the real work happens later on a
// background loop's own schedule" shape) -- the caller (this Step: tests
// only; Step 52: a real trigger-condition evaluation) has already run
// automation.ValidateTargets against targets before calling this.
func (q *Queries) CreateAutomationInvocation(ctx context.Context, arg CreateAutomationInvocationParams) (AutomationInvocation, error) {
	row := q.db.QueryRow(ctx, createAutomationInvocation, arg.AutomationID, arg.Targets, arg.TotalRuns)
	var i AutomationInvocation
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Status,
		&i.Targets,
		&i.TotalRuns,
		&i.FannedOutAt,
		&i.FailureCountedAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationInvocation = `-- name: GetAutomationInvocation :one
SELECT id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at FROM automation_invocations
WHERE id = $1
`

func (q *Queries) GetAutomationInvocation(ctx context.Context, id pgtype.UUID) (AutomationInvocation, error) {
	row := q.db.QueryRow(ctx, getAutomationInvocation, id)
	var i AutomationInvocation
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Status,
		&i.Targets,
		&i.TotalRuns,
		&i.FannedOutAt,
		&i.FailureCountedAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDueForFanOut = `-- name: ListDueForFanOut :many
SELECT id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at FROM automation_invocations
WHERE fanned_out_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Every invocation not yet claimed for fan-out, oldest first, locked FOR
// UPDATE SKIP LOCKED -- callers MUST run this inside the same transaction
// that subsequently calls ClaimAutomationInvocationForFanOut on each
// returned row, mirroring ListDueImageBuilds/ListDuePendingOutbox's own
// identical claim-batch precedent exactly.
func (q *Queries) ListDueForFanOut(ctx context.Context, limit int32) ([]AutomationInvocation, error) {
	rows, err := q.db.Query(ctx, listDueForFanOut, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationInvocation
	for rows.Next() {
		var i AutomationInvocation
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.Status,
			&i.Targets,
			&i.TotalRuns,
			&i.FannedOutAt,
			&i.FailureCountedAt,
			&i.ClosedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAutomationInvocationFailureCounted = `-- name: MarkAutomationInvocationFailureCounted :one
UPDATE automation_invocations
SET failure_counted_at = now()
WHERE id = $1 AND failure_counted_at IS NULL
RETURNING id, automation_id, status, targets, total_runs, fanned_out_at, failure_counted_at, closed_at, created_at
`

// §3.5's own literal CAS idiom: "UPDATE ... WHERE failure_counted_at IS
// NULL" -- called only for an invocation CloseAutomationInvocation just
// decided is Failed, in the SAME transaction as
// LockAutomationForUpdate/ApplyFailureStrike (queries/automations.sql),
// guarding the failure-strike CONSEQUENCE against being applied twice
// even if this invocation's own close-out is somehow re-attempted after a
// crash between the two (internal/domain/automation/doc.go's own "two
// independent CAS guards, not one" section).
func (q *Queries) MarkAutomationInvocationFailureCounted(ctx context.Context, id pgtype.UUID) (AutomationInvocation, error) {
	row := q.db.QueryRow(ctx, markAutomationInvocationFailureCounted, id)
	var i AutomationInvocation
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Status,
		&i.Targets,
		&i.TotalRuns,
		&i.FannedOutAt,
		&i.FailureCountedAt,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}
