// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatgpt_link_attempts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatGPTLinkAttempt = `-- name: CreateChatGPTLinkAttempt :one

INSERT INTO chatgpt_link_attempts (user_id, device_auth_id, user_code, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, device_auth_id, user_code, last_polled_at, expires_at, created_at
`

type CreateChatGPTLinkAttemptParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	DeviceAuthID string             `json:"device_auth_id"`
	UserCode     string             `json:"user_code"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing ChatGPTLinkAttemptStore -- the ChatGPT-account-OAuth
// link flow's own short-lived nonce table (Step 59, §29.3,
// migrations/000062_chatgpt_oauth_credentials.up.sql). Mirrors identity_
// link_prompts.sql's own query shapes (queries/identity_link_prompts.sql)
// adapted for a direct per-user link rather than a provider+external-id
// match -- see that file's own doc comment for the shared "no UNIQUE
// constraint, resend/reuse policy lives in app code" precedent this table
// also follows.
func (q *Queries) CreateChatGPTLinkAttempt(ctx context.Context, arg CreateChatGPTLinkAttemptParams) (ChatgptLinkAttempt, error) {
	row := q.db.QueryRow(ctx, createChatGPTLinkAttempt,
		arg.UserID,
		arg.DeviceAuthID,
		arg.UserCode,
		arg.ExpiresAt,
	)
	var i ChatgptLinkAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceAuthID,
		&i.UserCode,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatGPTLinkAttempt = `-- name: DeleteChatGPTLinkAttempt :exec
DELETE FROM chatgpt_link_attempts
WHERE id = $1
`

func (q *Queries) DeleteChatGPTLinkAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatGPTLinkAttempt, id)
	return err
}

const deleteChatGPTLinkAttemptsForUser = `-- name: DeleteChatGPTLinkAttemptsForUser :exec
DELETE FROM chatgpt_link_attempts
WHERE user_id = $1
`

// Cleanup once a user's link genuinely succeeds (mirrors identity_link_
// prompts.sql's own DeleteLinkPromptsForProviderAndExternalID) -- any
// other still-pending attempt for that same user is deleted too, so a
// stale device code minted before this success can never be polled again
// afterward.
func (q *Queries) DeleteChatGPTLinkAttemptsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatGPTLinkAttemptsForUser, userID)
	return err
}

const getLatestChatGPTLinkAttemptForUser = `-- name: GetLatestChatGPTLinkAttemptForUser :one
SELECT id, user_id, device_auth_id, user_code, last_polled_at, expires_at, created_at FROM chatgpt_link_attempts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// internal/app/chatgptlink's own re-entry check (mirrors identity_link_
// prompts.sql's GetLatestLinkPromptForProviderAndExternalID exactly): the
// most recently created attempt for this user, if any, so StartLink can
// decide whether a still-live one already exists before minting a brand
// new device code on every single "Connect ChatGPT account" click -- and
// so PollLink can find the current attempt to poll against.
func (q *Queries) GetLatestChatGPTLinkAttemptForUser(ctx context.Context, userID pgtype.UUID) (ChatgptLinkAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestChatGPTLinkAttemptForUser, userID)
	var i ChatgptLinkAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceAuthID,
		&i.UserCode,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateChatGPTLinkAttemptLastPolledAt = `-- name: UpdateChatGPTLinkAttemptLastPolledAt :one
UPDATE chatgpt_link_attempts
SET last_polled_at = $2
WHERE id = $1
RETURNING id, user_id, device_auth_id, user_code, last_polled_at, expires_at, created_at
`

type UpdateChatGPTLinkAttemptLastPolledAtParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastPolledAt pgtype.Timestamptz `json:"last_polled_at"`
}

// Throttles PollLink's own upstream deviceauth/token call to at most one
// attempt per server-provided interval (§29.3 point 2) -- the caller reads
// last_polled_at first, decides whether enough time has passed, and only
// then calls this to record a fresh attempt timestamp before actually
// polling upstream.
func (q *Queries) UpdateChatGPTLinkAttemptLastPolledAt(ctx context.Context, arg UpdateChatGPTLinkAttemptLastPolledAtParams) (ChatgptLinkAttempt, error) {
	row := q.db.QueryRow(ctx, updateChatGPTLinkAttemptLastPolledAt, arg.ID, arg.LastPolledAt)
	var i ChatgptLinkAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceAuthID,
		&i.UserCode,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
