// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract_drift.sql

package sqlcgen

import (
	"context"
)

const getContractDriftSnapshot = `-- name: GetContractDriftSnapshot :one

SELECT repo_key, last_repo_sha, last_contracts_fingerprint, updated_at FROM contract_drift_snapshots WHERE repo_key = $1
`

// Queries backing contract_drift_snapshots (Step 27, "mocking + contract
// drift", §14.3, migrations/000025_mock_config_contract_drift.up.sql). See
// that migration's own doc comment for the table's shape and the
// last_contracts_fingerprint=="" sentinel meaning. Written/read ONLY by
// app/sessionactor/contractdrift.go's own checkContractDrift, for
// mock_configured Environments only.
// checkContractDrift's own "read the last recorded snapshot for this
// repo" lookup -- pgx.ErrNoRows means no snapshot has ever been recorded
// for repo_key yet (contractdrift.HasDrifted's own "first sighting"
// case), NOT an error the caller need treat specially beyond that.
func (q *Queries) GetContractDriftSnapshot(ctx context.Context, repoKey string) (ContractDriftSnapshot, error) {
	row := q.db.QueryRow(ctx, getContractDriftSnapshot, repoKey)
	var i ContractDriftSnapshot
	err := row.Scan(
		&i.RepoKey,
		&i.LastRepoSha,
		&i.LastContractsFingerprint,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContractDriftSnapshot = `-- name: UpsertContractDriftSnapshot :exec
INSERT INTO contract_drift_snapshots (repo_key, last_repo_sha, last_contracts_fingerprint)
VALUES ($1, $2, $3)
ON CONFLICT (repo_key) DO UPDATE SET last_repo_sha = $2, last_contracts_fingerprint = $3, updated_at = now()
`

type UpsertContractDriftSnapshotParams struct {
	RepoKey                  string `json:"repo_key"`
	LastRepoSha              string `json:"last_repo_sha"`
	LastContractsFingerprint string `json:"last_contracts_fingerprint"`
}

// checkContractDrift's own best-effort "persist the latest snapshot for
// next time" write, run regardless of whether drift was detected this
// round -- ON CONFLICT DO UPDATE so a repo already tracked simply has its
// (last_repo_sha, last_contracts_fingerprint, updated_at) overwritten with
// the current round's own resolved values.
func (q *Queries) UpsertContractDriftSnapshot(ctx context.Context, arg UpsertContractDriftSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertContractDriftSnapshot, arg.RepoKey, arg.LastRepoSha, arg.LastContractsFingerprint)
	return err
}
