// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digestchannels.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDistinctReposWithRecentSessions = `-- name: ListDistinctReposWithRecentSessions :many
SELECT DISTINCT repo_full_name FROM github_pr_sessions
WHERE claimed_at > $1
LIMIT $2
`

type ListDistinctReposWithRecentSessionsParams struct {
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	Limit     int32              `json:"limit"`
}

// internal/app/digest.Pump's own per-tick repo enumeration -- every
// DISTINCT repo_full_name github_pr_sessions has claimed since sinceTime,
// bounded by limit (§21.1's own "bounded from day one" discipline). The
// SAME "no canonical registry of every repo Narvi manages" gap
// githubapi/listopenprs.go's own doc comment already names -- this is
// the best available substitute, exactly like internal/app/automerge's
// own reliance on repo_settings for its OWN repo enumeration.
func (q *Queries) ListDistinctReposWithRecentSessions(ctx context.Context, arg ListDistinctReposWithRecentSessionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctReposWithRecentSessions, arg.ClaimedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var repo_full_name string
		if err := rows.Scan(&repo_full_name); err != nil {
			return nil, err
		}
		items = append(items, repo_full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinearOrganizationsForRepoSince = `-- name: ListLinearOrganizationsForRepoSince :many
SELECT DISTINCT las.organization_id
FROM linear_agent_sessions las
JOIN github_pr_sessions gps ON gps.session_id = las.session_id
WHERE gps.repo_full_name = $1 AND las.created_at > $2
`

type ListLinearOrganizationsForRepoSinceParams struct {
	RepoFullName string             `json:"repo_full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// The Linear sibling of ListSlackChannelsForRepoSince above --
// organization_id is the closest existing granularity Linear's own
// schema carries (linear_agent_sessions has no distinct "channel"/"team"
// concept, migrations/000030's own doc comment); mirrors
// linearNotifier.resolveAccessToken's own identical per-organization
// credential scoping (internal/app/outboxworker/linearnotifier.go).
func (q *Queries) ListLinearOrganizationsForRepoSince(ctx context.Context, arg ListLinearOrganizationsForRepoSinceParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listLinearOrganizationsForRepoSince, arg.RepoFullName, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var organization_id string
		if err := rows.Scan(&organization_id); err != nil {
			return nil, err
		}
		items = append(items, organization_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackChannelsForRepoSince = `-- name: ListSlackChannelsForRepoSince :many

SELECT DISTINCT sts.channel_id
FROM slack_thread_sessions sts
JOIN github_pr_sessions gps ON gps.session_id = sts.session_id
WHERE gps.repo_full_name = $1 AND sts.created_at > $2
`

type ListSlackChannelsForRepoSinceParams struct {
	RepoFullName string             `json:"repo_full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Queries backing internal/app/digest's own channel-discovery step
// (Step 62, §21.3) -- "per-repo/per-channel ... reusing existing
// session-thread association tables, never a second, separate repo<->
// channel mechanism". Each query joins the SAME github_pr_sessions table
// (repo_full_name) already used throughout this codebase's own review
// machinery against an EXISTING channel-identity table
// (slack_thread_sessions/linear_agent_sessions) -- no new table.
// Every DISTINCT Slack channel a review session for repoFullName has
// threaded through since sinceTime -- "this channel has recently hosted
// this repo's own review activity", the one signal a digest's own
// per-repo/per-channel scoping needs.
func (q *Queries) ListSlackChannelsForRepoSince(ctx context.Context, arg ListSlackChannelsForRepoSinceParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSlackChannelsForRepoSince, arg.RepoFullName, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
