// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one

INSERT INTO environments (path_scope, mock_configured, contracts_path, docker_required, egress_policy_mode, egress_policy_allowlist)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, path_scope, mock_configured, created_at, contracts_path, docker_required, egress_policy_mode, egress_policy_allowlist
`

type CreateEnvironmentParams struct {
	PathScope             []byte  `json:"path_scope"`
	MockConfigured        bool    `json:"mock_configured"`
	ContractsPath         *string `json:"contracts_path"`
	DockerRequired        bool    `json:"docker_required"`
	EgressPolicyMode      *string `json:"egress_policy_mode"`
	EgressPolicyAllowlist []byte  `json:"egress_policy_allowlist"`
}

// Queries backing the environments table (§14.1, migrations/000021_environments.up.sql,
// migrations/000025_mock_config_contract_drift.up.sql). Environment rows are
// created INLINE by httpapi.CreateSession only, when a caller supplies a
// non-empty pathScope AND/OR a mockConfig -- there is no standalone
// create/list/update Environment endpoint in this codebase (see
// migrations/000021_environments.up.sql's own scope decision).
// path_scope is the caller-supplied pathScope, already validated by
// internal/domain/environment.ValidatePathScope BEFORE this is ever
// called -- this query performs no validation of its own. mock_configured/
// contracts_path (§14.3, "mocking + contract drift") are the caller's
// own resolved mockConfig presence/path -- mock_configured=false and
// contracts_path=NULL (the ordinary, unscoped-mock case) when the
// request's mockConfig key was absent; see httpapi.CreateSession's own
// doc comment for exactly how these three are resolved from one request.
// docker_required/egress_policy_mode/egress_policy_allowlist (
// §27.5/§27.6) are the caller's own resolved docker/egressPolicy presence
// -- docker_required=false and both egress_policy_* columns NULL (the
// ordinary, no-substrate-requirement case) when the request carried
// neither key. The egress_policy_allowlist value stored here is the
// CUSTOMER's own configured allowlist ONLY -- see migrations/
// 000095_environment_docker_egress.up.sql's own doc comment for why the
// non-negotiable floor is never persisted into this column.
// Extended in place, as a single INSERT accepting all five columns,
// rather than adding a second UPDATE query: environments rows are ALWAYS
// created inline at session-creation time (this table's own doc comment),
// never updated afterward, so there is no separate "attach a mock_config
// later" path for a second query to serve.
func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.PathScope,
		arg.MockConfigured,
		arg.ContractsPath,
		arg.DockerRequired,
		arg.EgressPolicyMode,
		arg.EgressPolicyAllowlist,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.PathScope,
		&i.MockConfigured,
		&i.CreatedAt,
		&i.ContractsPath,
		&i.DockerRequired,
		&i.EgressPolicyMode,
		&i.EgressPolicyAllowlist,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, path_scope, mock_configured, created_at, contracts_path, docker_required, egress_policy_mode, egress_policy_allowlist FROM environments
WHERE id = $1
`

// app/sessionactor/contractdrift.go's own checkContractDrift reads a
// spawn/restore plan's environment_id back via this lookup, to check
// MockConfigured and read ContractsPath.
func (q *Queries) GetEnvironment(ctx context.Context, id pgtype.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.PathScope,
		&i.MockConfigured,
		&i.CreatedAt,
		&i.ContractsPath,
		&i.DockerRequired,
		&i.EgressPolicyMode,
		&i.EgressPolicyAllowlist,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, path_scope, mock_configured, created_at, contracts_path, docker_required, egress_policy_mode, egress_policy_allowlist FROM environments
ORDER BY created_at DESC
`

// §12.2 item 5: the first standalone READ over every environments
// row that exists, newest-first -- this table's own doc comment above is
// explicit that create/update stay inline-at-session-creation-time only;
// this query adds no write path, only the discoverability a "Settings ->
// Environments" screen and every environment-scoped §27 sub-screen
// (sandbox-secrets/opencode-config/cloud-identity-bindings/cluster-binding,
// all already keyed by environments.id) need to enumerate valid ids at all.
func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.PathScope,
			&i.MockConfigured,
			&i.CreatedAt,
			&i.ContractsPath,
			&i.DockerRequired,
			&i.EgressPolicyMode,
			&i.EgressPolicyAllowlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
