// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (session_id, type, payload) VALUES ($1, $2, $3)
RETURNING id, session_id, type, payload, created_at
`

type CreateEventParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Type      string      `json:"type"`
	Payload   []byte      `json:"payload"`
}

// Queries backing EventStore (§4.3, §6.1's append-only per-session event
// log). Just CreateEvent for now -- reads (cursor-paginated fetch_history)
// land with the client WS hub (Steps 18+).
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.SessionID, arg.Type, arg.Payload)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
