// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_actor_link_notices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGitHubActorLinkNotice = `-- name: ClaimGitHubActorLinkNotice :one
INSERT INTO github_actor_link_notices (repo_full_name, pr_number, commenter_id, notified_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name, pr_number, commenter_id)
DO UPDATE SET notified_at = now()
WHERE github_actor_link_notices.notified_at <= now() - make_interval(secs => $4::float8)
RETURNING repo_full_name, pr_number, commenter_id, notified_at, (xmax = 0) AS inserted
`

type ClaimGitHubActorLinkNoticeParams struct {
	RepoFullName string  `json:"repo_full_name"`
	PrNumber     int32   `json:"pr_number"`
	CommenterID  int64   `json:"commenter_id"`
	TtlSeconds   float64 `json:"ttl_seconds"`
}

type ClaimGitHubActorLinkNoticeRow struct {
	RepoFullName string             `json:"repo_full_name"`
	PrNumber     int32              `json:"pr_number"`
	CommenterID  int64              `json:"commenter_id"`
	NotifiedAt   pgtype.Timestamptz `json:"notified_at"`
	Inserted     bool               `json:"inserted"`
}

// Atomically decides whether THIS caller is the one responsible for
// posting a fresh "please sign in" reply for (repo_full_name, pr_number,
// commenter_id) right now, and records that decision in the SAME
// statement as the check -- unlike GetGitHubActorLinkNotice followed by a
// LATER UpsertGitHubActorLinkNotice call (with a real GitHub API POST in
// between), which leaves a genuine window for two concurrent webhook
// deliveries of the identical (repo, PR, commenter) to both observe "no
// live notice yet" and both post (the exact race this query exists to
// close).
//
// Mirrors ClaimWebhookDelivery's own "(xmax = 0) AS inserted" first-
// writer-wins idiom (webhookdeliveries.sql) exactly, extended with a WHERE
// clause on the DO UPDATE branch: when an existing row's own notified_at
// is still within the caller-supplied TTL (sqlc.arg(ttl_seconds), whole
// seconds), that row is left completely untouched and this statement's
// own RETURNING clause emits NO row for it at all -- Postgres never fires
// RETURNING for a DO UPDATE whose WHERE condition evaluates false, and a
// :one query with zero rows surfaces to the Go caller as pgx.ErrNoRows.
// The caller reads that as "someone else (a concurrent delivery, or an
// earlier mention within the TTL) already claimed this notice -- do not
// post again"; any row returned (fresh insert OR a past-TTL update) means
// "you are the one, go ahead and post".
func (q *Queries) ClaimGitHubActorLinkNotice(ctx context.Context, arg ClaimGitHubActorLinkNoticeParams) (ClaimGitHubActorLinkNoticeRow, error) {
	row := q.db.QueryRow(ctx, claimGitHubActorLinkNotice,
		arg.RepoFullName,
		arg.PrNumber,
		arg.CommenterID,
		arg.TtlSeconds,
	)
	var i ClaimGitHubActorLinkNoticeRow
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommenterID,
		&i.NotifiedAt,
		&i.Inserted,
	)
	return i, err
}

const getGitHubActorLinkNotice = `-- name: GetGitHubActorLinkNotice :one

SELECT repo_full_name, pr_number, commenter_id, notified_at FROM github_actor_link_notices
WHERE repo_full_name = $1 AND pr_number = $2 AND commenter_id = $3
`

type GetGitHubActorLinkNoticeParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	CommenterID  int64  `json:"commenter_id"`
}

// Queries backing GitHubActorLinkNoticeStore (batch fix/deny-unlinked-
// github-actors' own anti-spam dedupe table,
// migrations/000043_github_actor_link_notices.up.sql -- see that
// migration's own doc comment for the full "why this key, why not
// identity_link_prompts/github_pr_sessions/webhook_deliveries" reasoning).
// The caller's own re-entry check (a second/later mention from the SAME
// still-unlinked commenter, on the SAME PR): the most recent notice row,
// if any, so the caller can compare notified_at against
// platform.Timeouts.GitHubActorNoticeTTL before deciding whether to post
// another reply -- mirrors GetLatestLinkPromptForProviderAndExternalID's
// own identical "fetch, then TTL-compare" shape (identity_link_prompts.sql).
func (q *Queries) GetGitHubActorLinkNotice(ctx context.Context, arg GetGitHubActorLinkNoticeParams) (GithubActorLinkNotice, error) {
	row := q.db.QueryRow(ctx, getGitHubActorLinkNotice, arg.RepoFullName, arg.PrNumber, arg.CommenterID)
	var i GithubActorLinkNotice
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommenterID,
		&i.NotifiedAt,
	)
	return i, err
}

const upsertGitHubActorLinkNotice = `-- name: UpsertGitHubActorLinkNotice :one
INSERT INTO github_actor_link_notices (repo_full_name, pr_number, commenter_id, notified_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name, pr_number, commenter_id)
DO UPDATE SET notified_at = now()
RETURNING repo_full_name, pr_number, commenter_id, notified_at
`

type UpsertGitHubActorLinkNoticeParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	CommenterID  int64  `json:"commenter_id"`
}

// Records (or refreshes) that this exact (repo, PR, commenter) has just
// been told to sign in -- called only once GetGitHubActorLinkNotice above
// has already established no still-live notice exists. ON CONFLICT DO
// UPDATE (not DO NOTHING): once the prior notice's own TTL has elapsed, a
// fresh mention should reset notified_at to NOW, not silently no-op and
// leave the stale timestamp in place.
//
// NOTE: kept as a low-level store primitive (and its own dedicated
// integration test, githubactorlinknotice_store_integration_test.go) but
// no longer used by actornotauthorizedreply.go's own notify workflow --
// see ClaimGitHubActorLinkNotice below for why a separate Get-then-later-
// Upsert pair, with a real GitHub API call in between, is not safe for
// that job.
func (q *Queries) UpsertGitHubActorLinkNotice(ctx context.Context, arg UpsertGitHubActorLinkNoticeParams) (GithubActorLinkNotice, error) {
	row := q.db.QueryRow(ctx, upsertGitHubActorLinkNotice, arg.RepoFullName, arg.PrNumber, arg.CommenterID)
	var i GithubActorLinkNotice
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.CommenterID,
		&i.NotifiedAt,
	)
	return i, err
}
