// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one

INSERT INTO identities (user_id, provider, external_id, email, email_verified, linked_via, access_token_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted
`

type CreateIdentityParams struct {
	UserID               pgtype.UUID       `json:"user_id"`
	Provider             IdentityProvider  `json:"provider"`
	ExternalID           string            `json:"external_id"`
	Email                *string           `json:"email"`
	EmailVerified        bool              `json:"email_verified"`
	LinkedVia            IdentityLinkedVia `json:"linked_via"`
	AccessTokenEncrypted []byte            `json:"access_token_encrypted"`
}

// Queries backing IdentityStore (§13.2 identity graph,
// migrations/000003_identities.up.sql + migrations/000017_auth_v1.up.sql's
// own access_token_encrypted column). CreateIdentity links a fresh user to
// a provider identity at first-sign-in time.
// GetIdentityByProviderAndExternalID is the OAuth callback's own
// returning-vs-first-time-sign-in check. UpdateIdentityAccessToken
// re-encrypts and stores a fresh provider token on every successful
// sign-in of an ALREADY-linked identity (GitHub's own classic OAuth tokens
// don't expire, but re-storing on each login is harmless and keeps the
// stored token fresh if the user ever re-authorized with different
// scopes).
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.Email,
		arg.EmailVerified,
		arg.LinkedVia,
		arg.AccessTokenEncrypted,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM identities
WHERE id = $1
`

// Backs the admin manual-unlink endpoint. Scoped to id, but the caller
// (httpapi/members.go) always re-checks the row's own UserID against the
// path's userID first -- this query alone would just as happily delete
// ANY user's identity by id, so it is never safe to call directly from
// an id a caller hasn't already verified belongs to the expected user.
func (q *Queries) DeleteIdentity(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentity, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityByProviderAndExternalID = `-- name: GetIdentityByProviderAndExternalID :one
SELECT id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted FROM identities
WHERE provider = $1 AND external_id = $2
`

type GetIdentityByProviderAndExternalIDParams struct {
	Provider   IdentityProvider `json:"provider"`
	ExternalID string           `json:"external_id"`
}

func (q *Queries) GetIdentityByProviderAndExternalID(ctx context.Context, arg GetIdentityByProviderAndExternalIDParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderAndExternalID, arg.Provider, arg.ExternalID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const getIdentityByUserAndProvider = `-- name: GetIdentityByUserAndProvider :one
SELECT id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted FROM identities
WHERE user_id = $1 AND provider = $2
`

type GetIdentityByUserAndProviderParams struct {
	UserID   pgtype.UUID      `json:"user_id"`
	Provider IdentityProvider `json:"provider"`
}

// §9.3 ("e2e happy path")'s own scm-credentials endpoint uses this to
// find a session's created_by user's GitHub identity (to decrypt its
// access_token_encrypted) -- the OAuth callback's own lookup above goes
// the other direction (provider+external_id -> user).
func (q *Queries) GetIdentityByUserAndProvider(ctx context.Context, arg GetIdentityByUserAndProviderParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByUserAndProvider, arg.UserID, arg.Provider)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const listIdentitiesForUser = `-- name: ListIdentitiesForUser :many
SELECT id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted FROM identities
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ExternalID,
			&i.Email,
			&i.EmailVerified,
			&i.LinkedVia,
			&i.CreatedAt,
			&i.AccessTokenEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedIdentityUserIDsByEmail = `-- name: ListVerifiedIdentityUserIDsByEmail :many

SELECT DISTINCT user_id FROM identities
WHERE email_verified = true AND lower(email) = lower($1)
`

// §13.2 ("identities + full RBAC", §13.2/§13.3) additions --
// ListVerifiedIdentityUserIDsByEmail is the auto-link algorithm's own
// "match against ... verified identity emails" half (the OTHER half,
// users.primary_email, is GetUserByPrimaryEmail in users.sql);
// ListIdentitiesForUser/DeleteIdentity back the members API's own
// "linked identities incl. pending-link state" listing and admin
// manual-unlink endpoint (§13.2 point 5, "admin can force-link").
// DISTINCT: the SAME user could plausibly have two verified identities
// (e.g. Slack AND Linear) sharing one email -- this must still count as
// ONE match for §13.2's own "exactly one verified match" test, never two,
// so a caller combining this with GetUserByPrimaryEmail's own single
// result must dedupe by user_id regardless; DISTINCT here just avoids
// handing back an already-known duplicate in the common case.
func (q *Queries) ListVerifiedIdentityUserIDsByEmail(ctx context.Context, lower string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listVerifiedIdentityUserIDsByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentityAccessToken = `-- name: UpdateIdentityAccessToken :one
UPDATE identities
SET access_token_encrypted = $2
WHERE id = $1
RETURNING id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted
`

type UpdateIdentityAccessTokenParams struct {
	ID                   pgtype.UUID `json:"id"`
	AccessTokenEncrypted []byte      `json:"access_token_encrypted"`
}

func (q *Queries) UpdateIdentityAccessToken(ctx context.Context, arg UpdateIdentityAccessTokenParams) (Identity, error) {
	row := q.db.QueryRow(ctx, updateIdentityAccessToken, arg.ID, arg.AccessTokenEncrypted)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}
