// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one

INSERT INTO identities (user_id, provider, external_id, email, email_verified, linked_via, access_token_encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted
`

type CreateIdentityParams struct {
	UserID               pgtype.UUID       `json:"user_id"`
	Provider             IdentityProvider  `json:"provider"`
	ExternalID           string            `json:"external_id"`
	Email                *string           `json:"email"`
	EmailVerified        bool              `json:"email_verified"`
	LinkedVia            IdentityLinkedVia `json:"linked_via"`
	AccessTokenEncrypted []byte            `json:"access_token_encrypted"`
}

// Queries backing IdentityStore (§13.2 identity graph,
// migrations/000003_identities.up.sql + migrations/000017_auth_v1.up.sql's
// own access_token_encrypted column). CreateIdentity links a fresh user to
// a provider identity at first-sign-in time.
// GetIdentityByProviderAndExternalID is the OAuth callback's own
// returning-vs-first-time-sign-in check. UpdateIdentityAccessToken
// re-encrypts and stores a fresh provider token on every successful
// sign-in of an ALREADY-linked identity (GitHub's own classic OAuth tokens
// don't expire, but re-storing on each login is harmless and keeps the
// stored token fresh if the user ever re-authorized with different
// scopes).
func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.Email,
		arg.EmailVerified,
		arg.LinkedVia,
		arg.AccessTokenEncrypted,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const getIdentityByProviderAndExternalID = `-- name: GetIdentityByProviderAndExternalID :one
SELECT id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted FROM identities
WHERE provider = $1 AND external_id = $2
`

type GetIdentityByProviderAndExternalIDParams struct {
	Provider   IdentityProvider `json:"provider"`
	ExternalID string           `json:"external_id"`
}

func (q *Queries) GetIdentityByProviderAndExternalID(ctx context.Context, arg GetIdentityByProviderAndExternalIDParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderAndExternalID, arg.Provider, arg.ExternalID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const getIdentityByUserAndProvider = `-- name: GetIdentityByUserAndProvider :one
SELECT id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted FROM identities
WHERE user_id = $1 AND provider = $2
`

type GetIdentityByUserAndProviderParams struct {
	UserID   pgtype.UUID      `json:"user_id"`
	Provider IdentityProvider `json:"provider"`
}

// Step 21 ("e2e happy path")'s own scm-credentials endpoint uses this to
// find a session's created_by user's GitHub identity (to decrypt its
// access_token_encrypted) -- the OAuth callback's own lookup above goes
// the other direction (provider+external_id -> user).
func (q *Queries) GetIdentityByUserAndProvider(ctx context.Context, arg GetIdentityByUserAndProviderParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByUserAndProvider, arg.UserID, arg.Provider)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const updateIdentityAccessToken = `-- name: UpdateIdentityAccessToken :one
UPDATE identities
SET access_token_encrypted = $2
WHERE id = $1
RETURNING id, user_id, provider, external_id, email, email_verified, linked_via, created_at, access_token_encrypted
`

type UpdateIdentityAccessTokenParams struct {
	ID                   pgtype.UUID `json:"id"`
	AccessTokenEncrypted []byte      `json:"access_token_encrypted"`
}

func (q *Queries) UpdateIdentityAccessToken(ctx context.Context, arg UpdateIdentityAccessTokenParams) (Identity, error) {
	row := q.db.QueryRow(ctx, updateIdentityAccessToken, arg.ID, arg.AccessTokenEncrypted)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Email,
		&i.EmailVerified,
		&i.LinkedVia,
		&i.CreatedAt,
		&i.AccessTokenEncrypted,
	)
	return i, err
}
