// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linearagentsessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimLinearAgentSession = `-- name: ClaimLinearAgentSession :one

INSERT INTO linear_agent_sessions (agent_session_id, organization_id)
VALUES ($1, $2)
ON CONFLICT (agent_session_id) DO UPDATE SET agent_session_id = linear_agent_sessions.agent_session_id
RETURNING agent_session_id, session_id, organization_id, created_at, (xmax = 0) AS inserted
`

type ClaimLinearAgentSessionParams struct {
	AgentSessionID string `json:"agent_session_id"`
	OrganizationID string `json:"organization_id"`
}

type ClaimLinearAgentSessionRow struct {
	AgentSessionID string             `json:"agent_session_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Inserted       bool               `json:"inserted"`
}

// Queries backing LinearAgentSessionStore ("Linear ingress",
// §8.10 -- migrations/000030_linear_agent_sessions.up.sql's own doc
// comment has the full "why this table exists at all" writeup).
// Atomic first-writer-wins claim on agent_session_id -- the SAME
// "(xmax = 0) AS inserted" idiom ClaimWebhookDelivery already establishes
// (postgres/queries/webhookdeliveries.sql), reused here for a DIFFERENT
// identity (Linear's own AgentSession id, not a webhook delivery id).
// Inserted=true means THIS call is the one that gets to actually create
// the Narvi session (SetSessionID below, once createSessionCore returns);
// Inserted=false means another `created` event for the SAME agent session
// already claimed it first -- the caller must never create a second
// session, regardless of whether that earlier claim has finished
// attaching its own session_id yet.
func (q *Queries) ClaimLinearAgentSession(ctx context.Context, arg ClaimLinearAgentSessionParams) (ClaimLinearAgentSessionRow, error) {
	row := q.db.QueryRow(ctx, claimLinearAgentSession, arg.AgentSessionID, arg.OrganizationID)
	var i ClaimLinearAgentSessionRow
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}

const getLinearAgentSessionByAgentSessionID = `-- name: GetLinearAgentSessionByAgentSessionID :one
SELECT agent_session_id, session_id, organization_id, created_at FROM linear_agent_sessions
WHERE agent_session_id = $1
`

// The `prompted`-event lookup: which Narvi session (if any) does this
// Linear agent session already back? A pgx.ErrNoRows result, OR a row
// whose session_id is still NULL (the `created` claim won by a
// still-in-flight createSessionCore call), both mean "nothing to route
// this prompt to yet" -- the caller treats both the same way (log + ack,
// never fabricate a session).
func (q *Queries) GetLinearAgentSessionByAgentSessionID(ctx context.Context, agentSessionID string) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, getLinearAgentSessionByAgentSessionID, agentSessionID)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearAgentSessionBySessionID = `-- name: GetLinearAgentSessionBySessionID :one
SELECT agent_session_id, session_id, organization_id, created_at FROM linear_agent_sessions
WHERE session_id = $1
`

// The REVERSE lookup §5.1 ("outbox delivery") needs: given a
// session_id, which agent_session_id/organization_id does it back? Backed
// by migrations/000030_linear_agent_sessions.up.sql's own already-existing
// linear_agent_sessions_session_id_idx (Step 34 added this index up
// front). A pgx.ErrNoRows result means this session was never created via
// a Linear agent session -- the caller skips enqueuing a Linear
// notification entirely rather than fabricating one.
func (q *Queries) GetLinearAgentSessionBySessionID(ctx context.Context, sessionID pgtype.UUID) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, getLinearAgentSessionBySessionID, sessionID)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const releaseLinearAgentSessionClaim = `-- name: ReleaseLinearAgentSessionClaim :exec
DELETE FROM linear_agent_sessions WHERE agent_session_id = $1 AND session_id IS NULL
`

// Audit-fix addition (H3, "webhook claim/release parity"): un-claims a
// first-writer-wins row this same request just won via
// ClaimLinearAgentSession (Inserted=true), but failed to actually
// complete -- an authorization denial or a CreateSessionCore error (both
// happen BEFORE any real session/turn/dispatch exists, so releasing is
// always safe here). Without this, either would leave the row permanently
// stuck with a NULL session_id: every future prompt/redelivery for that
// agent_session_id is dropped forever as "still being claimed" (webhook.go's
// own handlePrompted), with no recovery short of DB surgery -- mirrors
// ReleaseWebhookDelivery's own reasoning (postgres/queries/
// webhookdeliveries.sql) for a DIFFERENT claim identity.
//
// Deliberately NOT called for a SetSessionID failure (a later, HIGH audit
// fix, "releasing the linear_agent_sessions claim after a SetSessionID
// failure can spawn a duplicate, independently-dispatched agent"): by the
// time SetSessionID could ever fail, createSessionCore has ALREADY
// committed a real, DISPATCHED session -- releasing this claim then would
// let a redelivery spawn a SECOND, independently-dispatched session for the
// same agent_session_id instead of closing a gap. See webhook.go's own
// handleCreated/setSessionIDWithRetry for the retry that replaces this call
// on that specific branch.
//
// The `session_id IS NULL` guard is load-bearing: a row that already has
// a REAL session_id attached backs a session that genuinely exists (and
// may already be in progress) -- releasing THAT row would let a later,
// unrelated event re-claim the SAME agent_session_id and attempt to
// create a SECOND, colliding session, exactly the coalescing failure this
// table exists to prevent (migrations/000030_linear_agent_sessions.up.sql's
// own doc comment). Scoping the DELETE to session_id IS NULL makes this
// safe to call unconditionally on every post-claim failure branch: if
// SetSessionID already won before this call runs, the DELETE simply
// matches zero rows, and the real, already-attached session is left
// completely untouched.
func (q *Queries) ReleaseLinearAgentSessionClaim(ctx context.Context, agentSessionID string) error {
	_, err := q.db.Exec(ctx, releaseLinearAgentSessionClaim, agentSessionID)
	return err
}

const setLinearAgentSessionSessionID = `-- name: SetLinearAgentSessionSessionID :exec
UPDATE linear_agent_sessions
SET session_id = $2
WHERE agent_session_id = $1
`

type SetLinearAgentSessionSessionIDParams struct {
	AgentSessionID string      `json:"agent_session_id"`
	SessionID      pgtype.UUID `json:"session_id"`
}

// Attaches the real Narvi session id to a row this same request just won
// the claim on (ClaimLinearAgentSession's Inserted=true branch) -- run
// AFTER createSessionCore's own transaction has already committed, so a
// createSessionCore failure never leaves a claimed agent_session_id
// pointing at a session that doesn't exist.
func (q *Queries) SetLinearAgentSessionSessionID(ctx context.Context, arg SetLinearAgentSessionSessionIDParams) error {
	_, err := q.db.Exec(ctx, setLinearAgentSessionSessionID, arg.AgentSessionID, arg.SessionID)
	return err
}
