// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linearagentsessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimLinearAgentSession = `-- name: ClaimLinearAgentSession :one

INSERT INTO linear_agent_sessions (agent_session_id, organization_id)
VALUES ($1, $2)
ON CONFLICT (agent_session_id) DO UPDATE SET agent_session_id = linear_agent_sessions.agent_session_id
RETURNING agent_session_id, session_id, organization_id, created_at, (xmax = 0) AS inserted
`

type ClaimLinearAgentSessionParams struct {
	AgentSessionID string `json:"agent_session_id"`
	OrganizationID string `json:"organization_id"`
}

type ClaimLinearAgentSessionRow struct {
	AgentSessionID string             `json:"agent_session_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Inserted       bool               `json:"inserted"`
}

// Queries backing LinearAgentSessionStore (Step 34, "Linear ingress",
// §8.10 -- migrations/000030_linear_agent_sessions.up.sql's own doc
// comment has the full "why this table exists at all" writeup).
// Atomic first-writer-wins claim on agent_session_id -- the SAME
// "(xmax = 0) AS inserted" idiom ClaimWebhookDelivery already establishes
// (postgres/queries/webhookdeliveries.sql), reused here for a DIFFERENT
// identity (Linear's own AgentSession id, not a webhook delivery id).
// Inserted=true means THIS call is the one that gets to actually create
// the Narvi session (SetSessionID below, once createSessionCore returns);
// Inserted=false means another `created` event for the SAME agent session
// already claimed it first -- the caller must never create a second
// session, regardless of whether that earlier claim has finished
// attaching its own session_id yet.
func (q *Queries) ClaimLinearAgentSession(ctx context.Context, arg ClaimLinearAgentSessionParams) (ClaimLinearAgentSessionRow, error) {
	row := q.db.QueryRow(ctx, claimLinearAgentSession, arg.AgentSessionID, arg.OrganizationID)
	var i ClaimLinearAgentSessionRow
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}

const getLinearAgentSessionByAgentSessionID = `-- name: GetLinearAgentSessionByAgentSessionID :one
SELECT agent_session_id, session_id, organization_id, created_at FROM linear_agent_sessions
WHERE agent_session_id = $1
`

// The `prompted`-event lookup: which Narvi session (if any) does this
// Linear agent session already back? A pgx.ErrNoRows result, OR a row
// whose session_id is still NULL (the `created` claim won by a
// still-in-flight createSessionCore call), both mean "nothing to route
// this prompt to yet" -- the caller treats both the same way (log + ack,
// never fabricate a session).
func (q *Queries) GetLinearAgentSessionByAgentSessionID(ctx context.Context, agentSessionID string) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, getLinearAgentSessionByAgentSessionID, agentSessionID)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getLinearAgentSessionBySessionID = `-- name: GetLinearAgentSessionBySessionID :one
SELECT agent_session_id, session_id, organization_id, created_at FROM linear_agent_sessions
WHERE session_id = $1
`

// The REVERSE lookup Step 35 ("outbox delivery") needs: given a
// session_id, which agent_session_id/organization_id does it back? Backed
// by migrations/000030_linear_agent_sessions.up.sql's own already-existing
// linear_agent_sessions_session_id_idx (Step 34 added this index up
// front). A pgx.ErrNoRows result means this session was never created via
// a Linear agent session -- the caller skips enqueuing a Linear
// notification entirely rather than fabricating one.
func (q *Queries) GetLinearAgentSessionBySessionID(ctx context.Context, sessionID pgtype.UUID) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, getLinearAgentSessionBySessionID, sessionID)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.SessionID,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const setLinearAgentSessionSessionID = `-- name: SetLinearAgentSessionSessionID :exec
UPDATE linear_agent_sessions
SET session_id = $2
WHERE agent_session_id = $1
`

type SetLinearAgentSessionSessionIDParams struct {
	AgentSessionID string      `json:"agent_session_id"`
	SessionID      pgtype.UUID `json:"session_id"`
}

// Attaches the real Narvi session id to a row this same request just won
// the claim on (ClaimLinearAgentSession's Inserted=true branch) -- run
// AFTER createSessionCore's own transaction has already committed, so a
// createSessionCore failure never leaves a claimed agent_session_id
// pointing at a session that doesn't exist.
func (q *Queries) SetLinearAgentSessionSessionID(ctx context.Context, arg SetLinearAgentSessionSessionIDParams) error {
	_, err := q.db.Exec(ctx, setLinearAgentSessionSessionID, arg.AgentSessionID, arg.SessionID)
	return err
}
