// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidcsigningkeys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCSigningKey = `-- name: CreateOIDCSigningKey :one

INSERT INTO oidc_signing_keys (kid, private_key_encrypted, public_jwk)
VALUES ($1, $2, $3)
RETURNING kid, private_key_encrypted, public_jwk, created_at, retired_at
`

type CreateOIDCSigningKeyParams struct {
	Kid                 string `json:"kid"`
	PrivateKeyEncrypted []byte `json:"private_key_encrypted"`
	PublicJwk           []byte `json:"public_jwk"`
}

// Queries backing OIDCSigningKeyStore (Step 73a, "cloud identity: OIDC
// issuer, bindings, minting", §27.3) --
// migrations/000092_oidc_signing_keys.up.sql. private_key_encrypted is
// ciphertext (platform.EncryptToken output) end to end here; nothing in
// this file, or the Go store wrapping it, ever decrypts -- that happens
// exactly once, server-side, in the minting endpoint (internal/adapters/
// inbound/httpapi/cloudidentitytoken.go), to sign one token with the
// current active key.
// kid is CP-generated (internal/adapters/outbound/oidcsigning), never
// caller-supplied -- a collision would violate this table's own PRIMARY
// KEY, which the caller (OIDCSigningKeyStore.Rotate) treats as
// unreachable in practice given kid's own generation entropy, not
// specially handled.
func (q *Queries) CreateOIDCSigningKey(ctx context.Context, arg CreateOIDCSigningKeyParams) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, createOIDCSigningKey, arg.Kid, arg.PrivateKeyEncrypted, arg.PublicJwk)
	var i OidcSigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyEncrypted,
		&i.PublicJwk,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getActiveOIDCSigningKey = `-- name: GetActiveOIDCSigningKey :one
SELECT kid, private_key_encrypted, public_jwk, created_at, retired_at FROM oidc_signing_keys WHERE retired_at IS NULL
`

// The minting endpoint's own "which key signs a brand-new token" read --
// pgx.ErrNoRows means no key has ever been provisioned (or every key has
// somehow been retired with none replacing it, which RotateSigningKeys'
// own atomic retire-then-insert makes unreachable in practice) -- the
// caller treats either identically: mint fails closed, "no active signing
// key configured".
func (q *Queries) GetActiveOIDCSigningKey(ctx context.Context) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, getActiveOIDCSigningKey)
	var i OidcSigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyEncrypted,
		&i.PublicJwk,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listPublishableOIDCSigningKeys = `-- name: ListPublishableOIDCSigningKeys :many
SELECT kid, private_key_encrypted, public_jwk, created_at, retired_at FROM oidc_signing_keys
WHERE retired_at IS NULL OR retired_at > $1
ORDER BY created_at
`

// The JWKS endpoint's own single read: every key still inside its own
// publish window -- the active key (retired_at IS NULL) plus any retired
// key whose own retired_at + the caller's overlap-window argument has not
// yet elapsed (sqlc.arg('cutoff'), the caller's own already-computed
// now() - overlapWindow: a row publishes while retired_at > cutoff, i.e.
// retirement happened more recently than one full overlap window ago).
// Computing the cutoff in Go (internal/domain/oidckey, pure, given now +
// the configured overlap window) rather than as SQL arithmetic here keeps
// every clock read in the adapter layer, matching platform.Clock's own
// "domain gets values passed in" discipline (§11) even though this query
// itself lives in the adapter, not domain -- one fewer place a duration
// literal could sneak into raw SQL.
func (q *Queries) ListPublishableOIDCSigningKeys(ctx context.Context, cutoff pgtype.Timestamptz) ([]OidcSigningKey, error) {
	rows, err := q.db.Query(ctx, listPublishableOIDCSigningKeys, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcSigningKey
	for rows.Next() {
		var i OidcSigningKey
		if err := rows.Scan(
			&i.Kid,
			&i.PrivateKeyEncrypted,
			&i.PublicJwk,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireOIDCSigningKey = `-- name: RetireOIDCSigningKey :one
UPDATE oidc_signing_keys
SET retired_at = $1
WHERE kid = $2 AND retired_at IS NULL
RETURNING kid, private_key_encrypted, public_jwk, created_at, retired_at
`

type RetireOIDCSigningKeyParams struct {
	RetiredAt pgtype.Timestamptz `json:"retired_at"`
	Kid       string             `json:"kid"`
}

// Marks kid retired as of the caller's own now() -- the FIRST half of a
// rotation (OIDCSigningKeyStore.Rotate calls this, then
// CreateOIDCSigningKey, in the SAME transaction). A no-op WHERE clause
// guard (retired_at IS NULL) makes this idempotent against ever
// double-retiring an already-retired key, though the caller's own
// transaction already prevents that in practice.
func (q *Queries) RetireOIDCSigningKey(ctx context.Context, arg RetireOIDCSigningKeyParams) (OidcSigningKey, error) {
	row := q.db.QueryRow(ctx, retireOIDCSigningKey, arg.RetiredAt, arg.Kid)
	var i OidcSigningKey
	err := row.Scan(
		&i.Kid,
		&i.PrivateKeyEncrypted,
		&i.PublicJwk,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}
