// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEntry = `-- name: ClaimOutboxEntry :one
UPDATE outbox
SET attempts = attempts + 1, next_attempt_at = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type ClaimOutboxEntryParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

// The claim half of the pump's own two-step (claim-then-attempt-outside-
// any-transaction) shape: bumps next_attempt_at forward by the caller's
// own OutboxClaimDuration protection window and increments attempts,
// committed BEFORE the real notifier call is ever attempted -- mirrors
// ClaimImageBuild's own "attempt_count counts ATTEMPTS made, not merely
// failures" convention exactly, so domain/outbox.EvaluateBackoff is later
// asked to schedule (or dead-letter) THIS attempt using the post-increment
// count. Guarded by "AND status = 'pending'" so a stale/already-superseded
// row (should be impossible given ListDuePendingOutboxEntries' own WHERE
// clause, but defensive, mirroring RecordImageBuildSuccess/Failure's own
// identical guard) is a harmless no-op.
func (q *Queries) ClaimOutboxEntry(ctx context.Context, arg ClaimOutboxEntryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, claimOutboxEntry, arg.ID, arg.NextAttemptAt)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const createOutboxEntry = `-- name: CreateOutboxEntry :one

INSERT INTO outbox (session_id, kind, payload)
VALUES ($1, $2, $3)
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type CreateOutboxEntryParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
}

// Queries backing Outbox (§4.3, §5.1). CreateOutboxEntry/GetOutboxEntry
// prove the pipeline end to end (Step 31); the remaining five back Step
// 35's ("outbox delivery") own claim/attempt/record delivery-worker loop
// (internal/app/outboxworker), mirroring internal/adapters/outbound/
// postgres/queries/image_builds.sql's own ListDue/Claim/RecordSuccess/
// RecordFailure shape closely -- see that file's own doc comments for the
// general "claim inside one transaction, attempt outside any transaction"
// discipline this mirrors.
//
// Unlike image_builds, the outbox table has no third, in-flight status
// distinct from pending/delivered/dead_letter (migrations/000010_outbox.
// up.sql's own outbox_status enum is exactly pending/delivered/
// dead_letter) -- so ClaimOutboxEntry below cannot flip status the way
// ClaimImageBuild flips to 'building'. Instead it bumps next_attempt_at
// forward by the caller's own claim-protection window (platform.Timeouts.
// OutboxClaimDuration), mirroring app/sessionactor/timerpump.go's own
// ClaimDueTimer precedent exactly -- see that query's own doc comment for
// why a provisional forward-bump at claim time is the correct mechanism
// here.
func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEntry, arg.SessionID, arg.Kind, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getOutboxEntry = `-- name: GetOutboxEntry :one
SELECT id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at FROM outbox
WHERE id = $1
`

func (q *Queries) GetOutboxEntry(ctx context.Context, id pgtype.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutboxEntry, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listDuePendingOutboxEntries = `-- name: ListDuePendingOutboxEntries :many
SELECT id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at FROM outbox
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY next_attempt_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// outboxworker.Builder's own poll query: every 'pending' row whose own
// next_attempt_at has elapsed, oldest-due first. FOR UPDATE SKIP LOCKED
// mirrors ListDueImageBuilds/ListDueTimers' own identical precedent --
// multiple control-plane pods may run this same background loop
// independently; SKIP LOCKED lets two concurrent pods each claim a
// DISJOINT batch instead of blocking on each other or double-claiming the
// same row.
func (q *Queries) ListDuePendingOutboxEntries(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, listDuePendingOutboxEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEntryDeadLetter = `-- name: MarkOutboxEntryDeadLetter :one
UPDATE outbox
SET status = 'dead_letter', last_error = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type MarkOutboxEntryDeadLetterParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

// Records a failed delivery attempt that has exhausted domain/outbox.
// MaxAttempts: status='dead_letter', last_error captures the notifier's
// own final error. Same "AND status = 'pending'" guard as
// MarkOutboxEntryDelivered/RecordOutboxEntryFailure above.
func (q *Queries) MarkOutboxEntryDeadLetter(ctx context.Context, arg MarkOutboxEntryDeadLetterParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, markOutboxEntryDeadLetter, arg.ID, arg.LastError)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEntryDelivered = `-- name: MarkOutboxEntryDelivered :one
UPDATE outbox
SET status = 'delivered', delivered_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

// Records a successful delivery: status='delivered', delivered_at=now().
// Guarded by "AND status = 'pending'", mirroring RecordImageBuildSuccess's
// own identical guard against a stale/already-superseded row.
func (q *Queries) MarkOutboxEntryDelivered(ctx context.Context, id pgtype.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, markOutboxEntryDelivered, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const recordOutboxEntryFailure = `-- name: RecordOutboxEntryFailure :one
UPDATE outbox
SET next_attempt_at = $2, last_error = $3
WHERE id = $1 AND status = 'pending'
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type RecordOutboxEntryFailureParams struct {
	ID            pgtype.UUID        `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
}

// Records a failed delivery attempt that is still eligible for another
// retry: next_attempt_at is the caller's own domain/outbox.EvaluateBackoff-
// computed value (overwriting ClaimOutboxEntry's own provisional bump
// above with the real decision), last_error captures the notifier's own
// error for observability. attempts is NOT incremented again here --
// ClaimOutboxEntry already counted this attempt. Same "AND status =
// 'pending'" guard as MarkOutboxEntryDelivered, for the identical reason.
func (q *Queries) RecordOutboxEntryFailure(ctx context.Context, arg RecordOutboxEntryFailureParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, recordOutboxEntryFailure, arg.ID, arg.NextAttemptAt, arg.LastError)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}
