// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEntry = `-- name: CreateOutboxEntry :one

INSERT INTO outbox (session_id, kind, payload)
VALUES ($1, $2, $3)
RETURNING id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at
`

type CreateOutboxEntryParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Kind      string      `json:"kind"`
	Payload   []byte      `json:"payload"`
}

// Queries backing Outbox (§4.3, §5.1). Just enough to prove the pipeline
// end to end (create + get) — the delivery worker lands in PR-35.
func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEntry, arg.SessionID, arg.Kind, arg.Payload)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getOutboxEntry = `-- name: GetOutboxEntry :one
SELECT id, session_id, kind, payload, status, attempts, next_attempt_at, delivered_at, last_error, created_at FROM outbox
WHERE id = $1
`

func (q *Queries) GetOutboxEntry(ctx context.Context, id pgtype.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutboxEntry, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}
