// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (session_id, user_id)
VALUES ($1, $2)
RETURNING id, session_id, user_id, joined_at, last_seen_at
`

type CreateParticipantParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// This table's own first WRITER (ListSessions' own mine_only join,
// sessions.sql, needs a real row to test its "joined" half against --
// see this file's own top comment: nothing wrote here before this
// either). Not yet called by any production code path (multiplayer
// presence, §8.11, still owns when a real participants row gets created
// in normal operation) -- exercised by listsessions_integration_test.go
// only, exactly like ParticipantExists was exercised with zero real rows
// to find before now.
func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.SessionID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.JoinedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const participantExists = `-- name: ParticipantExists :one

SELECT EXISTS (SELECT 1 FROM participants WHERE session_id = $1 AND user_id = $2)
`

type ParticipantExistsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Queries backing ParticipantStore (migrations/000011_participants.up.sql).
// ParticipantExists is §8.1's own first real reader of this table
// (§13.3's own stopgap authorization predicate, internal/adapters/inbound/
// httpapi/planauthz.go's canActOnPlan) -- nothing populates participants
// yet (§8.11's own "distinct, not-yet-scoped concern"), so this always
// returns false today; queried defensively anyway so canActOnPlan is
// already correct the moment a future Step starts writing rows here, with
// no change needed at this call site.
func (q *Queries) ParticipantExists(ctx context.Context, arg ParticipantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, participantExists, arg.SessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
