// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePlanIfAwaitingApproval = `-- name: ApprovePlanIfAwaitingApproval :execrows
UPDATE plans
SET status = 'approved', decided_at = now(), decided_by = $3
WHERE id = $1 AND session_id = $2 AND status = 'awaiting_approval'
`

type ApprovePlanIfAwaitingApprovalParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	DecidedBy pgtype.UUID `json:"decided_by"`
}

func (q *Queries) ApprovePlanIfAwaitingApproval(ctx context.Context, arg ApprovePlanIfAwaitingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePlanIfAwaitingApproval, arg.ID, arg.SessionID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPlan = `-- name: CreatePlan :one

INSERT INTO plans (session_id, turn_id, version, status, plan_model_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, turn_id, version, status, plan_model_id, created_at, decided_at, decided_by, slack_channel_id, slack_message_ts
`

type CreatePlanParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	TurnID      pgtype.UUID `json:"turn_id"`
	Version     int32       `json:"version"`
	Status      PlanStatus  `json:"status"`
	PlanModelID *string     `json:"plan_model_id"`
}

// Queries backing PlanStore ("plan mode, web", §8.1/§12.2 item
// 3), migrations/000034_plan_mode.up.sql.
//
// CreatePlan/SupersedePlan/ListPlanSummariesForSession back
// internal/app/sessionactor's own plan-row-creation hook (planrecord.go):
// ListPlanSummariesForSession feeds internal/domain/plan's pure
// NextVersion/ShouldSupersede functions; SupersedePlan is called (in the
// SAME transaction, before CreatePlan) for every plan id
// ShouldSupersede's own output names.
//
// ApprovePlanIfAwaitingApproval/RejectPlanIfAwaitingApproval are the
// guarded conditional updates backing POST .../plans/:planId/approve|
// reject (internal/adapters/inbound/httpapi/planapprove.go): "WHERE ...
// status = 'awaiting_approval'" makes first-verdict-wins a real,
// race-safe DB guarantee -- a losing concurrent caller (already decided
// by someone else, or a stale/wrong plan id) simply affects zero rows,
// observed via :execrows, never a partial or corrupting write.
func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.SessionID,
		arg.TurnID,
		arg.Version,
		arg.Status,
		arg.PlanModelID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.Version,
		&i.Status,
		&i.PlanModelID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.SlackChannelID,
		&i.SlackMessageTs,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one

SELECT id, session_id, turn_id, version, status, plan_model_id, created_at, decided_at, decided_by, slack_channel_id, slack_message_ts FROM plans WHERE id = $1
`

// Step 38 ("plan mode, cross-channel", §8.1/§13.3) additions.
//
// GetPlan backs httpapi.DecidePlanOnTx's own post-guarded-UPDATE re-fetch
// (decideplan.go): whether THIS call's own guarded UPDATE won or lost, it
// needs the plan's own CURRENT row -- on a win, to read back
// slack_channel_id/slack_message_ts for the cross-channel notify step; on a
// loss, to report the plan's own actual current status honestly (already
// approved/rejected/superseded by whichever OTHER entry point won) rather
// than a bare "conflict".
//
// SetPlanSlackMessageRef backs internal/app/outboxworker's own Slack
// plan-approval notifier: once (and only once) a real chat.postMessage call
// for this plan version succeeds, the message's own real channel+ts (Slack's
// own response, never invented/derived) is persisted so a LATER decision
// (from any entry point) can chat.update that exact message.
func (q *Queries) GetPlan(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.Version,
		&i.Status,
		&i.PlanModelID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.SlackChannelID,
		&i.SlackMessageTs,
	)
	return i, err
}

const listAwaitingApprovalPlans = `-- name: ListAwaitingApprovalPlans :many
SELECT
    plans.id, plans.session_id, plans.turn_id, plans.version, plans.status, plans.plan_model_id,
    plans.created_at, plans.decided_at, plans.decided_by, plans.slack_channel_id, plans.slack_message_ts,
    sessions.created_by AS session_created_by,
    sessions.title AS session_title
FROM plans
JOIN sessions ON sessions.id = plans.session_id
WHERE plans.status = 'awaiting_approval'
ORDER BY plans.created_at
`

type ListAwaitingApprovalPlansRow struct {
	ID               pgtype.UUID        `json:"id"`
	SessionID        pgtype.UUID        `json:"session_id"`
	TurnID           pgtype.UUID        `json:"turn_id"`
	Version          int32              `json:"version"`
	Status           PlanStatus         `json:"status"`
	PlanModelID      *string            `json:"plan_model_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	DecidedBy        pgtype.UUID        `json:"decided_by"`
	SlackChannelID   *string            `json:"slack_channel_id"`
	SlackMessageTs   *string            `json:"slack_message_ts"`
	SessionCreatedBy pgtype.UUID        `json:"session_created_by"`
	SessionTitle     *string            `json:"session_title"`
}

// Step 60 ("decision inbox: read model + API", §16.1)'s own
// awaiting_approval row source: every plan still 'awaiting_approval',
// joined with its own session for the (created_by, title) the app-layer
// aggregator needs both to render the row and to resolve own/joined RBAC
// (mirrors httpapi.canActOnPlan's own identical CreatedBy check,
// planauthz.go -- the OTHER half, a participants-table "joined" check, is
// a separate per-session query this one does not embed, since a plan's
// own UNIQUE-per-session "at most one awaiting_approval row" invariant
// (plans_one_awaiting_approval_per_session) already keeps this result set
// small). System-wide, unscoped by user -- this Step's own read model
// resolves per-user ELIGIBILITY at the app layer, not in this query.
// Ordered oldest-first (plans.created_at) -- the SAME "entered the queue"
// instant the app-layer aggregator's own ranking needs, with no further
// derivation required.
func (q *Queries) ListAwaitingApprovalPlans(ctx context.Context) ([]ListAwaitingApprovalPlansRow, error) {
	rows, err := q.db.Query(ctx, listAwaitingApprovalPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAwaitingApprovalPlansRow
	for rows.Next() {
		var i ListAwaitingApprovalPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.Version,
			&i.Status,
			&i.PlanModelID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.SlackChannelID,
			&i.SlackMessageTs,
			&i.SessionCreatedBy,
			&i.SessionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanSummariesForSession = `-- name: ListPlanSummariesForSession :many
SELECT id, version, status FROM plans
WHERE session_id = $1
ORDER BY version
`

type ListPlanSummariesForSessionRow struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
	Status  PlanStatus  `json:"status"`
}

// The minimal shape internal/domain/plan.Summary needs -- ordered by
// version so NextVersion's own "highest existing version" scan is
// reading them in a natural, human-debuggable order (not required for
// correctness, NextVersion scans the whole slice regardless).
func (q *Queries) ListPlanSummariesForSession(ctx context.Context, sessionID pgtype.UUID) ([]ListPlanSummariesForSessionRow, error) {
	rows, err := q.db.Query(ctx, listPlanSummariesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanSummariesForSessionRow
	for rows.Next() {
		var i ListPlanSummariesForSessionRow
		if err := rows.Scan(&i.ID, &i.Version, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansForSession = `-- name: ListPlansForSession :many
SELECT id, session_id, turn_id, version, status, plan_model_id, created_at, decided_at, decided_by, slack_channel_id, slack_message_ts FROM plans
WHERE session_id = $1
ORDER BY version
`

// Audit-fix batch (completeness/discoverability, M3): backs GET
// /api/sessions/:id/plans (internal/adapters/inbound/httpapi/plans.go) --
// the endpoint that closes the "approve/reject shipped with no way
// for a web client to ever discover a planId to approve" gap. Unlike
// ListPlanSummariesForSession above (an internal, minimal shape feeding
// internal/domain/plan's own NextVersion/ShouldSupersede), this returns
// every FULL plan row for sessionID -- ordered by version for the same
// "natural, human-debuggable order" reason -- so the handler can map each
// one to restdtos.Plan (contracts/rest/v1/dtos.schema.json) for a real,
// versioned v1->v2 history view.
func (q *Queries) ListPlansForSession(ctx context.Context, sessionID pgtype.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.Version,
			&i.Status,
			&i.PlanModelID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.SlackChannelID,
			&i.SlackMessageTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyDecidedPlans = `-- name: ListRecentlyDecidedPlans :many
SELECT id, session_id, turn_id, version, status, plan_model_id, created_at, decided_at, decided_by, slack_channel_id, slack_message_ts FROM plans
WHERE status IN ('approved', 'rejected') AND decided_at >= $1
ORDER BY decided_at DESC
LIMIT $2
`

type ListRecentlyDecidedPlansParams struct {
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	Limit     int32              `json:"limit"`
}

// Step 60 ("decision inbox: read model + API", §16.2)'s own decision-
// latency metric input for the plan-approval half of that computation
// (median time from an item ENTERING the queue -- a plan's own
// created_at -- to its ACTION -- decided_at): every plan decided (approved
// or rejected, from ANY entry point -- web/Slack/Linear all funnel
// through the SAME guarded UPDATE, decideplan.go) at or after $1, bounded
// by $2 (§21.1's own "bounded from day one" discipline -- an explicit
// recent window, never an unbounded historical scan).
func (q *Queries) ListRecentlyDecidedPlans(ctx context.Context, arg ListRecentlyDecidedPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listRecentlyDecidedPlans, arg.DecidedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.Version,
			&i.Status,
			&i.PlanModelID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.SlackChannelID,
			&i.SlackMessageTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPlanIfAwaitingApproval = `-- name: RejectPlanIfAwaitingApproval :execrows
UPDATE plans
SET status = 'rejected', decided_at = now(), decided_by = $3
WHERE id = $1 AND session_id = $2 AND status = 'awaiting_approval'
`

type RejectPlanIfAwaitingApprovalParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	DecidedBy pgtype.UUID `json:"decided_by"`
}

func (q *Queries) RejectPlanIfAwaitingApproval(ctx context.Context, arg RejectPlanIfAwaitingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPlanIfAwaitingApproval, arg.ID, arg.SessionID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPlanSlackMessageRef = `-- name: SetPlanSlackMessageRef :exec
UPDATE plans SET slack_channel_id = $2, slack_message_ts = $3 WHERE id = $1
`

type SetPlanSlackMessageRefParams struct {
	ID             pgtype.UUID `json:"id"`
	SlackChannelID *string     `json:"slack_channel_id"`
	SlackMessageTs *string     `json:"slack_message_ts"`
}

func (q *Queries) SetPlanSlackMessageRef(ctx context.Context, arg SetPlanSlackMessageRefParams) error {
	_, err := q.db.Exec(ctx, setPlanSlackMessageRef, arg.ID, arg.SlackChannelID, arg.SlackMessageTs)
	return err
}

const supersedePlan = `-- name: SupersedePlan :exec
UPDATE plans SET status = 'superseded'
WHERE id = $1 AND status = 'awaiting_approval'
`

// Guarded by "AND status = 'awaiting_approval'" even though every real
// caller (planrecord.go) only ever passes an id ShouldSupersede itself
// already filtered to StatusAwaitingApproval -- belt-and-suspenders
// against ever superseding an already-decided (approved/rejected) row,
// matching this migration's own doc comment ("only an awaiting_approval
// row ever gets superseded").
func (q *Queries) SupersedePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedePlan, id)
	return err
}
