// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePlanIfAwaitingApproval = `-- name: ApprovePlanIfAwaitingApproval :execrows
UPDATE plans
SET status = 'approved', decided_at = now(), decided_by = $3
WHERE id = $1 AND session_id = $2 AND status = 'awaiting_approval'
`

type ApprovePlanIfAwaitingApprovalParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	DecidedBy pgtype.UUID `json:"decided_by"`
}

func (q *Queries) ApprovePlanIfAwaitingApproval(ctx context.Context, arg ApprovePlanIfAwaitingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePlanIfAwaitingApproval, arg.ID, arg.SessionID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPlan = `-- name: CreatePlan :one

INSERT INTO plans (session_id, turn_id, version, status, plan_model_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, turn_id, version, status, plan_model_id, created_at, decided_at, decided_by
`

type CreatePlanParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	TurnID      pgtype.UUID `json:"turn_id"`
	Version     int32       `json:"version"`
	Status      PlanStatus  `json:"status"`
	PlanModelID *string     `json:"plan_model_id"`
}

// Queries backing PlanStore (Step 37, "plan mode, web", §8.1/§12.2 item
// 3), migrations/000034_plan_mode.up.sql.
//
// CreatePlan/SupersedePlan/ListPlanSummariesForSession back
// internal/app/sessionactor's own plan-row-creation hook (planrecord.go):
// ListPlanSummariesForSession feeds internal/domain/plan's pure
// NextVersion/ShouldSupersede functions; SupersedePlan is called (in the
// SAME transaction, before CreatePlan) for every plan id
// ShouldSupersede's own output names.
//
// ApprovePlanIfAwaitingApproval/RejectPlanIfAwaitingApproval are the
// guarded conditional updates backing POST .../plans/:planId/approve|
// reject (internal/adapters/inbound/httpapi/planapprove.go): "WHERE ...
// status = 'awaiting_approval'" makes first-verdict-wins a real,
// race-safe DB guarantee -- a losing concurrent caller (already decided
// by someone else, or a stale/wrong plan id) simply affects zero rows,
// observed via :execrows, never a partial or corrupting write.
func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.SessionID,
		arg.TurnID,
		arg.Version,
		arg.Status,
		arg.PlanModelID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnID,
		&i.Version,
		&i.Status,
		&i.PlanModelID,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const listPlanSummariesForSession = `-- name: ListPlanSummariesForSession :many
SELECT id, version, status FROM plans
WHERE session_id = $1
ORDER BY version
`

type ListPlanSummariesForSessionRow struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
	Status  PlanStatus  `json:"status"`
}

// The minimal shape internal/domain/plan.Summary needs -- ordered by
// version so NextVersion's own "highest existing version" scan is
// reading them in a natural, human-debuggable order (not required for
// correctness, NextVersion scans the whole slice regardless).
func (q *Queries) ListPlanSummariesForSession(ctx context.Context, sessionID pgtype.UUID) ([]ListPlanSummariesForSessionRow, error) {
	rows, err := q.db.Query(ctx, listPlanSummariesForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanSummariesForSessionRow
	for rows.Next() {
		var i ListPlanSummariesForSessionRow
		if err := rows.Scan(&i.ID, &i.Version, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPlanIfAwaitingApproval = `-- name: RejectPlanIfAwaitingApproval :execrows
UPDATE plans
SET status = 'rejected', decided_at = now(), decided_by = $3
WHERE id = $1 AND session_id = $2 AND status = 'awaiting_approval'
`

type RejectPlanIfAwaitingApprovalParams struct {
	ID        pgtype.UUID `json:"id"`
	SessionID pgtype.UUID `json:"session_id"`
	DecidedBy pgtype.UUID `json:"decided_by"`
}

func (q *Queries) RejectPlanIfAwaitingApproval(ctx context.Context, arg RejectPlanIfAwaitingApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPlanIfAwaitingApproval, arg.ID, arg.SessionID, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedePlan = `-- name: SupersedePlan :exec
UPDATE plans SET status = 'superseded'
WHERE id = $1 AND status = 'awaiting_approval'
`

// Guarded by "AND status = 'awaiting_approval'" even though every real
// caller (planrecord.go) only ever passes an id ShouldSupersede itself
// already filtered to StatusAwaitingApproval -- belt-and-suspenders
// against ever superseding an already-decided (approved/rejected) row,
// matching this migration's own doc comment ("only an awaiting_approval
// row ever gets superseded").
func (q *Queries) SupersedePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedePlan, id)
	return err
}
