// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providercredentials.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderCredential = `-- name: CreateProviderCredential :one

INSERT INTO provider_credentials (scope, scope_target_id, provider, value_encrypted)
VALUES ($1, $4, $2, $3)
RETURNING id, scope, scope_target_id, provider, value_encrypted, created_at, updated_at
`

type CreateProviderCredentialParams struct {
	Scope          ProviderCredentialScope    `json:"scope"`
	Provider       ProviderCredentialProvider `json:"provider"`
	ValueEncrypted []byte                     `json:"value_encrypted"`
	ScopeTargetID  *string                    `json:"scope_target_id"`
}

// Queries backing ProviderCredentialStore (Step 53, "provider credential
// injection", §25.1/§25.3) -- migrations/000056_provider_credentials.up.sql.
// value_encrypted is ciphertext (platform.EncryptToken output) end to
// end here; nothing in this file, or the Go store wrapping it, ever
// decrypts -- that happens exactly once, server-side, in the sandbox-
// facing delivery endpoint (internal/adapters/inbound/httpapi/
// providercredentialsdelivery.go), only for the ONE row Resolve picked as
// the winner.
// scope_target_id is sqlc.narg: NULL for a global-scoped row (the CHECK
// constraint provider_credentials_scope_target_id_shape enforces it can
// ONLY be NULL for scope='global'), non-NULL otherwise. A duplicate
// (scope, scope_target_id, provider) violates one of this table's own two
// partial unique indexes -- the caller (httpapi.CreateProviderCredential)
// maps that Postgres error into a 409 Conflict, never retried here.
func (q *Queries) CreateProviderCredential(ctx context.Context, arg CreateProviderCredentialParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, createProviderCredential,
		arg.Scope,
		arg.Provider,
		arg.ValueEncrypted,
		arg.ScopeTargetID,
	)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Provider,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderCredential = `-- name: DeleteProviderCredential :execrows
DELETE FROM provider_credentials WHERE id = $1
`

func (q *Queries) DeleteProviderCredential(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProviderCredential = `-- name: GetProviderCredential :one
SELECT id, scope, scope_target_id, provider, value_encrypted, created_at, updated_at FROM provider_credentials WHERE id = $1
`

func (q *Queries) GetProviderCredential(ctx context.Context, id pgtype.UUID) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, getProviderCredential, id)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Provider,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderCredentialsByScope = `-- name: ListProviderCredentialsByScope :many
SELECT id, scope, scope_target_id, provider, value_encrypted, created_at, updated_at FROM provider_credentials
WHERE scope = $1 AND scope_target_id IS NOT DISTINCT FROM $2
ORDER BY provider
`

type ListProviderCredentialsByScopeParams struct {
	Scope         ProviderCredentialScope `json:"scope"`
	ScopeTargetID *string                 `json:"scope_target_id"`
}

// Lists every row at exactly one (scope, scope_target_id) pair -- e.g.
// every provider configured for ONE repo, or every provider configured
// for ONE environment, or (scope='global', scope_target_id NULL) every
// global-scoped provider. scope_target_id is sqlc.narg (NULL for the
// global case) with an explicit IS NOT DISTINCT FROM comparison, since a
// plain "=" never matches NULL = NULL.
func (q *Queries) ListProviderCredentialsByScope(ctx context.Context, arg ListProviderCredentialsByScopeParams) ([]ProviderCredential, error) {
	rows, err := q.db.Query(ctx, listProviderCredentialsByScope, arg.Scope, arg.ScopeTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderCredential
	for rows.Next() {
		var i ProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeTargetID,
			&i.Provider,
			&i.ValueEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderCredentialsForResolution = `-- name: ListProviderCredentialsForResolution :many
SELECT id, scope, scope_target_id, provider, value_encrypted, created_at, updated_at FROM provider_credentials
WHERE scope = 'global'
   OR (scope = 'repo' AND scope_target_id = ANY($1::text[]))
   OR (scope = 'environment' AND scope_target_id IS NOT NULL AND scope_target_id = $2)
ORDER BY provider
`

type ListProviderCredentialsForResolutionParams struct {
	RepoFullNames []string `json:"repo_full_names"`
	EnvironmentID *string  `json:"environment_id"`
}

// The delivery endpoint's own single, session-scoped read: every
// candidate row (across ALL 3 scopes, for EVERY provider at once) that
// could possibly apply to one session -- the global row for each
// provider (always included), any repo-scoped row for one of this
// session's own repo_full_names, and the environment-scoped row for this
// session's own environment_id, if any. repo_full_names may be an empty
// array (matches nothing, never an error); environment_id is sqlc.narg,
// NULL when the session has none (matches nothing -- scope_target_id is
// NEVER NULL for an environment-scoped row, so "environment_id IS NULL"
// correctly excludes every environment-scoped row when the caller has no
// environment at all, rather than needing a separate branch). The caller
// (providercredentialsdelivery.go) groups the result by provider and runs
// internal/domain/providercredential.Resolve over each group.
func (q *Queries) ListProviderCredentialsForResolution(ctx context.Context, arg ListProviderCredentialsForResolutionParams) ([]ProviderCredential, error) {
	rows, err := q.db.Query(ctx, listProviderCredentialsForResolution, arg.RepoFullNames, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderCredential
	for rows.Next() {
		var i ProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeTargetID,
			&i.Provider,
			&i.ValueEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderCredentialValue = `-- name: UpdateProviderCredentialValue :one
UPDATE provider_credentials
SET value_encrypted = $2, updated_at = now()
WHERE id = $1
RETURNING id, scope, scope_target_id, provider, value_encrypted, created_at, updated_at
`

type UpdateProviderCredentialValueParams struct {
	ID             pgtype.UUID `json:"id"`
	ValueEncrypted []byte      `json:"value_encrypted"`
}

// Rotates ONLY the encrypted value -- scope/scope_target_id/provider are
// immutable once created (see providercredentials.go's own doc comment
// for why: changing what a row scopes to is modeled as delete-then-create,
// never an in-place identity change).
func (q *Queries) UpdateProviderCredentialValue(ctx context.Context, arg UpdateProviderCredentialValueParams) (ProviderCredential, error) {
	row := q.db.QueryRow(ctx, updateProviderCredentialValue, arg.ID, arg.ValueEncrypted)
	var i ProviderCredential
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Provider,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
