// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releasemanifestchecks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReleaseManifestCheck = `-- name: GetLatestReleaseManifestCheck :one
SELECT id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at FROM release_manifest_checks
WHERE repo_full_name = $1 AND pr_number = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestReleaseManifestCheckParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// (repo_full_name, pr_number)'s own most-recently-computed check --
// mirrors GetLatestReviewVerdict's own identical "one indexed lookup,
// ORDER BY created_at DESC LIMIT 1" shape. pgx.ErrNoRows means no
// manifest check has ever been persisted for this PR (a row predating
// or a check whose own Run() insert failed and was only ever delivered as
// a comment).
func (q *Queries) GetLatestReleaseManifestCheck(ctx context.Context, arg GetLatestReleaseManifestCheckParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, getLatestReleaseManifestCheck, arg.RepoFullName, arg.PrNumber)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
	)
	return i, err
}

const insertReleaseManifestCheck = `-- name: InsertReleaseManifestCheck :one

INSERT INTO release_manifest_checks (
    session_id, repo_full_name, pr_number, base_ref, head_ref,
    constituent_pr_count, coverage_partial,
    aggregate_review_triggered, aggregate_review_trigger_reasons,
    findings, merged_prs
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at
`

type InsertReleaseManifestCheckParams struct {
	SessionID                     pgtype.UUID `json:"session_id"`
	RepoFullName                  string      `json:"repo_full_name"`
	PrNumber                      int32       `json:"pr_number"`
	BaseRef                       string      `json:"base_ref"`
	HeadRef                       string      `json:"head_ref"`
	ConstituentPrCount            int32       `json:"constituent_pr_count"`
	CoveragePartial               bool        `json:"coverage_partial"`
	AggregateReviewTriggered      bool        `json:"aggregate_review_triggered"`
	AggregateReviewTriggerReasons []byte      `json:"aggregate_review_trigger_reasons"`
	Findings                      []byte      `json:"findings"`
	MergedPrs                     []byte      `json:"merged_prs"`
}

// Queries backing ReleaseManifestCheckStore (§12.2 item 9, §15.2/§15.3) -- see
// migrations/000097_release_manifest_checks.up.sql's own doc comment for
// the table's full design.
// The one write internal/app/releasereview.Run makes once it has computed
// this release PR's own manifest findings + aggregate-review trigger
// decision -- alongside, never instead of, its existing outbox-delivered
// comment (RenderManifestComment). Best-effort: a failure here is logged
// and Run simply continues to its own existing outbox enqueue, mirroring
// that function's own established "every internal failure is logged and
// this function simply returns" posture.
func (q *Queries) InsertReleaseManifestCheck(ctx context.Context, arg InsertReleaseManifestCheckParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, insertReleaseManifestCheck,
		arg.SessionID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.BaseRef,
		arg.HeadRef,
		arg.ConstituentPrCount,
		arg.CoveragePartial,
		arg.AggregateReviewTriggered,
		arg.AggregateReviewTriggerReasons,
		arg.Findings,
		arg.MergedPrs,
	)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
	)
	return i, err
}
