// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reposettings.sql

package sqlcgen

import (
	"context"
)

const getRepoSettings = `-- name: GetRepoSettings :one

SELECT repo_full_name, block_on_high_risk, created_at, updated_at FROM repo_settings WHERE repo_full_name = $1
`

// Queries backing RepoSettingsStore (§8.2/Step 47, §21.2): a small,
// extensible table of admin-configured, per-repo policy flags -- see
// migrations/000044_repo_settings.up.sql's own doc comment for the full
// "one shared table, not one bespoke table per toggle" design rationale.
// A missing row (pgx.ErrNoRows) means every flag defaults to its own safe
// value -- callers must NOT treat that as an error, see this table's own
// migration doc comment.
func (q *Queries) GetRepoSettings(ctx context.Context, repoFullName string) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, getRepoSettings, repoFullName)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoSettings = `-- name: UpsertRepoSettings :one
INSERT INTO repo_settings (repo_full_name, block_on_high_risk, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET block_on_high_risk = EXCLUDED.block_on_high_risk, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at
`

type UpsertRepoSettingsParams struct {
	RepoFullName    string `json:"repo_full_name"`
	BlockOnHighRisk bool   `json:"block_on_high_risk"`
}

// Idempotent create-or-update, keyed on repo_full_name -- an admin
// (re)setting block_on_high_risk always writes the full, current desired
// value rather than patching a delta, so a concurrent double-submit from
// the same admin settles on whichever write lands last, never a
// non-deterministic partial merge.
func (q *Queries) UpsertRepoSettings(ctx context.Context, arg UpsertRepoSettingsParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertRepoSettings, arg.RepoFullName, arg.BlockOnHighRisk)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
