// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewverdicts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReviewVerdict = `-- name: GetLatestReviewVerdict :one
SELECT id, repo_full_name, pr_number, head_sha, risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift, proposed_shippable, shippable, session_id, created_at FROM review_verdicts
WHERE repo_full_name = $1 AND pr_number = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestReviewVerdictParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// The DISTINCT ON (repo, pr_number) ... ORDER BY created_at DESC
// reduction §21.1 specifies -- scoped here to ONE (repo_full_name,
// pr_number) pair (the one shape every real caller -- the auto-approval
// eligibility engine, the decision inbox's own classification, the
// revalidate-at-click/at-merge paths -- actually needs), so this is a
// plain indexed lookup ORDER BY created_at DESC LIMIT 1, not a
// multi-row DISTINCT ON scan -- see ListLatestAutoApprovedInRepo below
// for the multi-PR, per-repo shape that DOES need real DISTINCT ON.
// pgx.ErrNoRows means no verdict has ever been posted for this PR.
func (q *Queries) GetLatestReviewVerdict(ctx context.Context, arg GetLatestReviewVerdictParams) (ReviewVerdict, error) {
	row := q.db.QueryRow(ctx, getLatestReviewVerdict, arg.RepoFullName, arg.PrNumber)
	var i ReviewVerdict
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.RiskLevel,
		&i.Premise,
		&i.BlastRadius,
		&i.FilesChanged,
		&i.TestsCoverage,
		&i.DocsDrift,
		&i.ProposedShippable,
		&i.Shippable,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertReviewVerdict = `-- name: InsertReviewVerdict :one

INSERT INTO review_verdicts (
    repo_full_name, pr_number, head_sha,
    risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift,
    proposed_shippable, shippable, session_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, repo_full_name, pr_number, head_sha, risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift, proposed_shippable, shippable, session_id, created_at
`

type InsertReviewVerdictParams struct {
	RepoFullName      string      `json:"repo_full_name"`
	PrNumber          int32       `json:"pr_number"`
	HeadSha           string      `json:"head_sha"`
	RiskLevel         string      `json:"risk_level"`
	Premise           string      `json:"premise"`
	BlastRadius       []byte      `json:"blast_radius"`
	FilesChanged      int32       `json:"files_changed"`
	TestsCoverage     string      `json:"tests_coverage"`
	DocsDrift         string      `json:"docs_drift"`
	ProposedShippable string      `json:"proposed_shippable"`
	Shippable         string      `json:"shippable"`
	SessionID         pgtype.UUID `json:"session_id"`
}

// Queries backing ReviewVerdictStore (Step 62, §21.1) -- see
// migrations/000067_review_verdicts.up.sql's own doc comment for the
// table's full append-only design.
// The ONE write this table ever accepts -- always an INSERT, never an
// UPDATE (see the table's own doc comment for why). Called from
// httpapi.PostReviewVerdict (reviewverdict.go), inside the SAME
// transaction as that handler's existing review_findings upserts and
// outbox write.
func (q *Queries) InsertReviewVerdict(ctx context.Context, arg InsertReviewVerdictParams) (ReviewVerdict, error) {
	row := q.db.QueryRow(ctx, insertReviewVerdict,
		arg.RepoFullName,
		arg.PrNumber,
		arg.HeadSha,
		arg.RiskLevel,
		arg.Premise,
		arg.BlastRadius,
		arg.FilesChanged,
		arg.TestsCoverage,
		arg.DocsDrift,
		arg.ProposedShippable,
		arg.Shippable,
		arg.SessionID,
	)
	var i ReviewVerdict
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.RiskLevel,
		&i.Premise,
		&i.BlastRadius,
		&i.FilesChanged,
		&i.TestsCoverage,
		&i.DocsDrift,
		&i.ProposedShippable,
		&i.Shippable,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestAutoApprovedInRepo = `-- name: ListLatestAutoApprovedInRepo :many
SELECT id, repo_full_name, pr_number, head_sha, risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift, proposed_shippable, shippable, session_id, created_at FROM (
    SELECT DISTINCT ON (repo_full_name, pr_number) id, repo_full_name, pr_number, head_sha, risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift, proposed_shippable, shippable, session_id, created_at
    FROM review_verdicts
    WHERE repo_full_name = $1 AND created_at > $2
    ORDER BY repo_full_name, pr_number, created_at DESC
) latest
WHERE shippable = 'auto'
ORDER BY created_at ASC
LIMIT $3
`

type ListLatestAutoApprovedInRepoParams struct {
	RepoFullName string             `json:"repo_full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Limit        int32              `json:"limit"`
}

// internal/app/automerge's own discovery query (§21.2 stage 2): every
// open-as-of-last-review-candidate PR in repoFullName whose LATEST
// verdict, within the bounded window, is Shippable == 'auto' -- the real
// multi-row DISTINCT ON (repo, pr_number) ... ORDER BY created_at DESC
// reduction §21.1 names, THEN filtered to shippable = 'auto' in an outer
// query (DISTINCT ON's own "first row per group" pick must be decided by
// created_at alone, before shippable can be tested, so the filter cannot
// fold into the same SELECT's own WHERE clause). This is a DISCOVERY
// aid only, bounded and cheap (no GitHub call) -- internal/app/
// decisioninbox.RevalidateForAutoMerge is what actually re-confirms each
// candidate live before anything merges (§21.2: "reuses the decision
// inbox's existing server-side re-validation-at-click contract
// unchanged"), so a candidate this query returns that has since gone
// stale (a new commit landed, CI flipped) is simply rejected there, never
// trusted as authority here.
func (q *Queries) ListLatestAutoApprovedInRepo(ctx context.Context, arg ListLatestAutoApprovedInRepoParams) ([]ReviewVerdict, error) {
	rows, err := q.db.Query(ctx, listLatestAutoApprovedInRepo, arg.RepoFullName, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVerdict
	for rows.Next() {
		var i ReviewVerdict
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.HeadSha,
			&i.RiskLevel,
			&i.Premise,
			&i.BlastRadius,
			&i.FilesChanged,
			&i.TestsCoverage,
			&i.DocsDrift,
			&i.ProposedShippable,
			&i.Shippable,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewVerdictsInWindow = `-- name: ListReviewVerdictsInWindow :many
SELECT id, repo_full_name, pr_number, head_sha, risk_level, premise, blast_radius, files_changed, tests_coverage, docs_drift, proposed_shippable, shippable, session_id, created_at FROM review_verdicts
WHERE repo_full_name = $1 AND created_at > $2
ORDER BY created_at ASC
LIMIT $3
`

type ListReviewVerdictsInWindowParams struct {
	RepoFullName string             `json:"repo_full_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Limit        int32              `json:"limit"`
}

// The analytics rollups' own shared bounded scan (§21.1: "every query
// against this history is bounded from day one") -- every verdict for
// repoFullName posted after sinceTime, oldest first. internal/app/
// reviewverdict's own Timeseries/TopRiskDrivers functions both reduce
// this SAME result set in memory (a pure, already-fetched-data
// transform, mirroring internal/domain/decisioninbox.MedianLatency's own
// "caller fetches, pure package reduces" split) rather than each issuing
// its own bespoke aggregate SQL query.
func (q *Queries) ListReviewVerdictsInWindow(ctx context.Context, arg ListReviewVerdictsInWindowParams) ([]ReviewVerdict, error) {
	rows, err := q.db.Query(ctx, listReviewVerdictsInWindow, arg.RepoFullName, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVerdict
	for rows.Next() {
		var i ReviewVerdict
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.HeadSha,
			&i.RiskLevel,
			&i.Premise,
			&i.BlastRadius,
			&i.FilesChanged,
			&i.TestsCoverage,
			&i.DocsDrift,
			&i.ProposedShippable,
			&i.Shippable,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
