// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewfalsepositivepatterns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFalsePositivePattern = `-- name: GetFalsePositivePattern :one
SELECT id, repo_full_name, comment_id, comment_type, reason, created_by, created_at, hit_count, last_hit_at, retired_at, retired_by FROM review_false_positive_patterns WHERE id = $1 AND repo_full_name = $2
`

type GetFalsePositivePatternParams struct {
	ID           pgtype.UUID `json:"id"`
	RepoFullName string      `json:"repo_full_name"`
}

// Looked up by the retire endpoint (patternID comes straight off the URL
// path, repoFullName off the route) -- SCOPED to repoFullName (audit fix:
// previously keyed on id alone, letting a pattern belonging to a
// DIFFERENT repo be retrieved through the wrong repo's URL) -- pgx.
// ErrNoRows means no such pattern exists IN THIS REPO at all, distinct
// from "exists (in this repo) but already retired"
// (RetireFalsePositivePattern's own guarded UPDATE reports that case
// separately -- see its own doc comment).
func (q *Queries) GetFalsePositivePattern(ctx context.Context, arg GetFalsePositivePatternParams) (ReviewFalsePositivePattern, error) {
	row := q.db.QueryRow(ctx, getFalsePositivePattern, arg.ID, arg.RepoFullName)
	var i ReviewFalsePositivePattern
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.CommentID,
		&i.CommentType,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.RetiredAt,
		&i.RetiredBy,
	)
	return i, err
}

const incrementFalsePositivePatternHitCount = `-- name: IncrementFalsePositivePatternHitCount :exec
UPDATE review_false_positive_patterns
SET hit_count = hit_count + 1, last_hit_at = now()
WHERE id = ANY($1::uuid[])
`

// §22.4's own hit-count bookkeeping: bumped once per pattern for every
// review pass that actually included it in the advisory block (§22.3:
// "injected into every review pass, first pass and re-review alike") --
// called with every active pattern's own id ListActiveFalsePositivePatterns
// just returned, immediately after rendering that same list into the
// advisory block (internal/app/reviewcontext.FetchFalsePositivePatterns).
// Best-effort bookkeeping only: a failure here must never fail the
// review turn whose prompt already carries the (successfully rendered)
// advisory block -- see that function's own doc comment.
func (q *Queries) IncrementFalsePositivePatternHitCount(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFalsePositivePatternHitCount, ids)
	return err
}

const listActiveFalsePositivePatterns = `-- name: ListActiveFalsePositivePatterns :many
SELECT id, repo_full_name, comment_id, comment_type, reason, created_by, created_at, hit_count, last_hit_at, retired_at, retired_by FROM review_false_positive_patterns
WHERE repo_full_name = $1 AND retired_at IS NULL
ORDER BY created_at ASC
`

// §22.3's own advisory-injection read: every currently-active (not
// retired) pattern for one repo, oldest-first (a stable, deterministic
// order, mirroring ListOpenAndRebuttedReviewFindings' own identical
// "byte-for-byte-repeatable render" reasoning, reviewfindings.sql).
func (q *Queries) ListActiveFalsePositivePatterns(ctx context.Context, repoFullName string) ([]ReviewFalsePositivePattern, error) {
	rows, err := q.db.Query(ctx, listActiveFalsePositivePatterns, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewFalsePositivePattern
	for rows.Next() {
		var i ReviewFalsePositivePattern
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.CommentID,
			&i.CommentType,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.HitCount,
			&i.LastHitAt,
			&i.RetiredAt,
			&i.RetiredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFalsePositivePatterns = `-- name: ListFalsePositivePatterns :many
SELECT id, repo_full_name, comment_id, comment_type, reason, created_by, created_at, hit_count, last_hit_at, retired_at, retired_by FROM review_false_positive_patterns
WHERE repo_full_name = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListFalsePositivePatternsParams struct {
	RepoFullName string `json:"repo_full_name"`
	Limit        int32  `json:"limit"`
}

// §22.4's own audit view: EVERY pattern for one repo, active or retired,
// newest-first (the natural read order for an audit/review screen --
// unlike ListActiveFalsePositivePatterns above, whose oldest-first order
// exists only to make repeated prompt renders deterministic). Bounded by
// limit, mirroring ListReviewFindingStatusesInWindow's own identical
// "bounded from day one" discipline (reviewfindings.sql) -- there is no
// unbounded "list everything, ever" query in this codebase for a
// maintainer-authored, potentially long-lived table like this one.
func (q *Queries) ListFalsePositivePatterns(ctx context.Context, arg ListFalsePositivePatternsParams) ([]ReviewFalsePositivePattern, error) {
	rows, err := q.db.Query(ctx, listFalsePositivePatterns, arg.RepoFullName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewFalsePositivePattern
	for rows.Next() {
		var i ReviewFalsePositivePattern
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.CommentID,
			&i.CommentType,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.HitCount,
			&i.LastHitAt,
			&i.RetiredAt,
			&i.RetiredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireFalsePositivePattern = `-- name: RetireFalsePositivePattern :one
UPDATE review_false_positive_patterns
SET retired_at = now(), retired_by = $2
WHERE id = $1 AND repo_full_name = $3 AND retired_at IS NULL
RETURNING id, repo_full_name, comment_id, comment_type, reason, created_by, created_at, hit_count, last_hit_at, retired_at, retired_by
`

type RetireFalsePositivePatternParams struct {
	ID           pgtype.UUID `json:"id"`
	RetiredBy    pgtype.UUID `json:"retired_by"`
	RepoFullName string      `json:"repo_full_name"`
}

// §22.4's own retirement write: a maintainer+ permanently excludes a
// stale/wrong pattern from future advisory injection. SCOPED to
// repo_full_name (audit fix: previously keyed on id alone -- the
// handler's own doc comment promises a 404 "if no pattern with this id
// exists in this repo at all", but that was unreachable: a pattern
// belonging to a DIFFERENT repo was happily retired through the wrong
// repo's URL, a real API-contract violation and a silent wrong-repo
// mutation via a stale UI id) AND guarded (WHERE retired_at IS NULL,
// CLAUDE.md/§11's own "guarded UPDATE ... WHERE for cross-writer
// transitions" rule) so retiring an ALREADY-retired pattern is a no-op
// that returns pgx.ErrNoRows (never a second, silently overwriting
// retired_at/retired_by) -- the caller (httpapi) tells "never existed in
// this repo" apart from "exists in this repo but already retired" via a
// follow-up GetFalsePositivePattern (also repo-scoped) read on this same
// ErrNoRows path.
func (q *Queries) RetireFalsePositivePattern(ctx context.Context, arg RetireFalsePositivePatternParams) (ReviewFalsePositivePattern, error) {
	row := q.db.QueryRow(ctx, retireFalsePositivePattern, arg.ID, arg.RetiredBy, arg.RepoFullName)
	var i ReviewFalsePositivePattern
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.CommentID,
		&i.CommentType,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.RetiredAt,
		&i.RetiredBy,
	)
	return i, err
}

const upsertFalsePositivePattern = `-- name: UpsertFalsePositivePattern :one

INSERT INTO review_false_positive_patterns (repo_full_name, comment_id, comment_type, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (comment_id, comment_type) DO UPDATE SET repo_full_name = review_false_positive_patterns.repo_full_name
RETURNING id, repo_full_name, comment_id, comment_type, reason, created_by, created_at, hit_count, last_hit_at, retired_at, retired_by, (xmax = 0) AS inserted
`

type UpsertFalsePositivePatternParams struct {
	RepoFullName string      `json:"repo_full_name"`
	CommentID    int64       `json:"comment_id"`
	CommentType  string      `json:"comment_type"`
	Reason       string      `json:"reason"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

type UpsertFalsePositivePatternRow struct {
	ID           pgtype.UUID        `json:"id"`
	RepoFullName string             `json:"repo_full_name"`
	CommentID    int64              `json:"comment_id"`
	CommentType  string             `json:"comment_type"`
	Reason       string             `json:"reason"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	HitCount     int32              `json:"hit_count"`
	LastHitAt    pgtype.Timestamptz `json:"last_hit_at"`
	RetiredAt    pgtype.Timestamptz `json:"retired_at"`
	RetiredBy    pgtype.UUID        `json:"retired_by"`
	Inserted     bool               `json:"inserted"`
}

// Queries backing FalsePositivePatternStore (Step 63, "review: learned
// false-positive patterns", §22.2/§22.4) -- see
// migrations/000073_review_false_positive_patterns.up.sql's own doc
// comment for the table's full design.
// Idempotent create keyed on (comment_id, comment_type) (§22.2: "keyed on
// the triggering comment id" -- comment_type joins that key because
// comment_id ALONE is not globally unique across GitHub's own
// issue_comment vs pull_request_review_comment id sequences, see this
// table's own migration doc comment) -- mirrors ClaimWebhookDelivery's
// own "(xmax = 0) AS inserted" self-referential-no-op-update idiom
// (webhookdeliveries.sql) exactly, NOT UpsertReviewFinding's "refresh one
// bookkeeping column on conflict" idiom: unlike a finding, which is
// legitimately re-reported on every later commit, a taught pattern is
// captured EXACTLY ONCE, by its own triggering comment -- a redelivered
// webhook or a retried command for the SAME (comment_id, comment_type)
// must leave every column (most importantly retired_at/hit_count, this
// row's own mutable lifecycle state) completely untouched, never reset
// back to "just taught, active, zero hits". Inserted (via "xmax = 0")
// lets the caller log whether this call captured a genuinely NEW pattern
// or just re-observed an already-known (comment_id, comment_type) pair,
// without a second SELECT.
func (q *Queries) UpsertFalsePositivePattern(ctx context.Context, arg UpsertFalsePositivePatternParams) (UpsertFalsePositivePatternRow, error) {
	row := q.db.QueryRow(ctx, upsertFalsePositivePattern,
		arg.RepoFullName,
		arg.CommentID,
		arg.CommentType,
		arg.Reason,
		arg.CreatedBy,
	)
	var i UpsertFalsePositivePatternRow
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.CommentID,
		&i.CommentType,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.HitCount,
		&i.LastHitAt,
		&i.RetiredAt,
		&i.RetiredBy,
		&i.Inserted,
	)
	return i, err
}
