// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxsecrets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSandboxSecret = `-- name: CreateSandboxSecret :one

INSERT INTO sandbox_secrets (scope, scope_target_id, name, value_encrypted)
VALUES ($1, $4, $2, $3)
RETURNING id, scope, scope_target_id, name, value_encrypted, created_at, updated_at
`

type CreateSandboxSecretParams struct {
	Scope          SandboxSecretScope `json:"scope"`
	Name           string             `json:"name"`
	ValueEncrypted []byte             `json:"value_encrypted"`
	ScopeTargetID  *string            `json:"scope_target_id"`
}

// Queries backing SandboxSecretStore (Step 72, "sandbox secrets &
// opencode config", §27.1) -- migrations/000090_sandbox_secrets.up.sql.
// value_encrypted is ciphertext (platform.EncryptToken output) end to end
// here; nothing in this file, or the Go store wrapping it, ever decrypts
// -- that happens exactly once, server-side, in the sandbox-facing
// delivery endpoint (internal/adapters/inbound/httpapi/
// sandboxsecretsdelivery.go), only for the winning row(s)
// providercredential.Resolve picks per name.
// scope_target_id is sqlc.narg: NULL for a global-scoped row (the CHECK
// constraint sandbox_secrets_scope_target_id_shape enforces it can ONLY
// be NULL for scope='global'), non-NULL otherwise. A duplicate (scope,
// scope_target_id, name) violates one of this table's own two partial
// unique indexes -- the caller (httpapi.CreateSandboxSecret) maps that
// Postgres error into a 409 Conflict, never retried here.
func (q *Queries) CreateSandboxSecret(ctx context.Context, arg CreateSandboxSecretParams) (SandboxSecret, error) {
	row := q.db.QueryRow(ctx, createSandboxSecret,
		arg.Scope,
		arg.Name,
		arg.ValueEncrypted,
		arg.ScopeTargetID,
	)
	var i SandboxSecret
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Name,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSandboxSecret = `-- name: DeleteSandboxSecret :execrows
DELETE FROM sandbox_secrets WHERE id = $1
`

func (q *Queries) DeleteSandboxSecret(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSandboxSecret, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSandboxSecret = `-- name: GetSandboxSecret :one
SELECT id, scope, scope_target_id, name, value_encrypted, created_at, updated_at FROM sandbox_secrets WHERE id = $1
`

func (q *Queries) GetSandboxSecret(ctx context.Context, id pgtype.UUID) (SandboxSecret, error) {
	row := q.db.QueryRow(ctx, getSandboxSecret, id)
	var i SandboxSecret
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Name,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSandboxSecretsByScope = `-- name: ListSandboxSecretsByScope :many
SELECT id, scope, scope_target_id, name, value_encrypted, created_at, updated_at FROM sandbox_secrets
WHERE scope = $1 AND scope_target_id IS NOT DISTINCT FROM $2
ORDER BY name
`

type ListSandboxSecretsByScopeParams struct {
	Scope         SandboxSecretScope `json:"scope"`
	ScopeTargetID *string            `json:"scope_target_id"`
}

// Lists every row at exactly one (scope, scope_target_id) pair -- e.g.
// every secret configured for ONE repo, or every secret configured for
// ONE environment, or (scope='global', scope_target_id NULL) every
// global-scoped secret. scope_target_id is sqlc.narg (NULL for the global
// case) with an explicit IS NOT DISTINCT FROM comparison, since a plain
// "=" never matches NULL = NULL.
func (q *Queries) ListSandboxSecretsByScope(ctx context.Context, arg ListSandboxSecretsByScopeParams) ([]SandboxSecret, error) {
	rows, err := q.db.Query(ctx, listSandboxSecretsByScope, arg.Scope, arg.ScopeTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SandboxSecret
	for rows.Next() {
		var i SandboxSecret
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeTargetID,
			&i.Name,
			&i.ValueEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxSecretsForResolution = `-- name: ListSandboxSecretsForResolution :many
SELECT id, scope, scope_target_id, name, value_encrypted, created_at, updated_at FROM sandbox_secrets
WHERE scope = 'global'
   OR (scope = 'repo' AND scope_target_id = ANY($1::text[]))
   OR (scope = 'environment' AND scope_target_id IS NOT NULL AND scope_target_id = $2)
ORDER BY name
`

type ListSandboxSecretsForResolutionParams struct {
	RepoFullNames []string `json:"repo_full_names"`
	EnvironmentID *string  `json:"environment_id"`
}

// The delivery endpoint's own single, session-scoped read: every
// candidate row (across every scope THIS Step actually resolves, for
// EVERY name at once) that could possibly apply to one session -- the
// global row for each name (always included), any repo-scoped row for
// one of this session's own repo_full_names, and the environment-scoped
// row for this session's own environment_id (if any). Deliberately NO
// 'automation' branch -- §27.1's own schema-only carve-out for that scope
// (see migrations/000090_sandbox_secrets.up.sql's own top comment):
// nothing calls this query with an automation id to match against, so an
// automation-scoped row (should one ever exist) is simply never a
// candidate, exactly as if it were absent. repo_full_names may be an
// empty array (matches nothing, never an error); environment_id is
// sqlc.narg, NULL when the session has none (matches nothing --
// scope_target_id is NEVER NULL for an environment-scoped row, so "IS
// NULL" correctly excludes every row of that scope when the caller has
// none at all, mirroring ListProviderCredentialsForResolution's own
// identical userID/environmentID convention). The caller
// (sandboxsecretsdelivery.go) groups the result by name and runs
// internal/domain/providercredential.Resolve over each group.
func (q *Queries) ListSandboxSecretsForResolution(ctx context.Context, arg ListSandboxSecretsForResolutionParams) ([]SandboxSecret, error) {
	rows, err := q.db.Query(ctx, listSandboxSecretsForResolution, arg.RepoFullNames, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SandboxSecret
	for rows.Next() {
		var i SandboxSecret
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeTargetID,
			&i.Name,
			&i.ValueEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandboxSecretValue = `-- name: UpdateSandboxSecretValue :one
UPDATE sandbox_secrets
SET value_encrypted = $2, updated_at = now()
WHERE id = $1
RETURNING id, scope, scope_target_id, name, value_encrypted, created_at, updated_at
`

type UpdateSandboxSecretValueParams struct {
	ID             pgtype.UUID `json:"id"`
	ValueEncrypted []byte      `json:"value_encrypted"`
}

// Rotates ONLY the encrypted value -- scope/scope_target_id/name are
// immutable once created (delete-then-create if a different scope/
// target/name is actually wanted), mirroring
// UpdateProviderCredentialValue's own identical posture.
func (q *Queries) UpdateSandboxSecretValue(ctx context.Context, arg UpdateSandboxSecretValueParams) (SandboxSecret, error) {
	row := q.db.QueryRow(ctx, updateSandboxSecretValue, arg.ID, arg.ValueEncrypted)
	var i SandboxSecret
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeTargetID,
		&i.Name,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
