// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentinelfixes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSentinelFix = `-- name: GetSentinelFix :one
SELECT id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at FROM sentinel_fixes
WHERE repo_full_name = $1 AND origin_pr_number = $2
`

type GetSentinelFixParams struct {
	RepoFullName   string `json:"repo_full_name"`
	OriginPrNumber int32  `json:"origin_pr_number"`
}

// A plain, unlocked read -- the merge-gating webhook's own lookup
// (§17.4), which does its own locking via GetSentinelFixForUpdate only
// once it already knows a row exists and is about to mutate it.
func (q *Queries) GetSentinelFix(ctx context.Context, arg GetSentinelFixParams) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, getSentinelFix, arg.RepoFullName, arg.OriginPrNumber)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSentinelFixByFixSession = `-- name: GetSentinelFixByFixSession :one
SELECT id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at FROM sentinel_fixes
WHERE fix_child_session_id = $1
`

// The reverse lookup pushpr.go's own createSentinelFixPRBestEffort needs,
// once the FIX session's own push_complete event arrives (that code path
// only ever has its OWN session id in hand, never the origin PR's number
// directly).
func (q *Queries) GetSentinelFixByFixSession(ctx context.Context, fixChildSessionID pgtype.UUID) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, getSentinelFixByFixSession, fixChildSessionID)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSentinelFixByID = `-- name: GetSentinelFixByID :one
SELECT id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at FROM sentinel_fixes WHERE id = $1
`

// The outbox worker's own idempotency check (internal/app/outboxworker's
// sentinelAutoFixNotifier): the outbox payload carries this row's own id
// (captured at claim time, reviewverdict.go), so a redelivered/retried
// outbox entry can cheaply check "has a child session already been
// spawned for this claim" without a second (repo, pr_number) round trip.
func (q *Queries) GetSentinelFixByID(ctx context.Context, id pgtype.UUID) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, getSentinelFixByID, id)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSentinelFixForUpdate = `-- name: GetSentinelFixForUpdate :one
SELECT id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at FROM sentinel_fixes
WHERE repo_full_name = $1 AND origin_pr_number = $2
FOR UPDATE
`

type GetSentinelFixForUpdateParams struct {
	RepoFullName   string `json:"repo_full_name"`
	OriginPrNumber int32  `json:"origin_pr_number"`
}

// Step TWO of the atomic claim: locks and reads the row Step one just
// ensured exists -- serializes any concurrent claimant for the SAME PR
// behind it, mirroring github_pr_sessions' own identical "SELECT ... FOR
// UPDATE" locking precedent.
func (q *Queries) GetSentinelFixForUpdate(ctx context.Context, arg GetSentinelFixForUpdateParams) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, getSentinelFixForUpdate, arg.RepoFullName, arg.OriginPrNumber)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSentinelFixIfAbsent = `-- name: InsertSentinelFixIfAbsent :execrows

INSERT INTO sentinel_fixes (repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repo_full_name, origin_pr_number) DO NOTHING
`

type InsertSentinelFixIfAbsentParams struct {
	RepoFullName          string      `json:"repo_full_name"`
	OriginPrNumber        int32       `json:"origin_pr_number"`
	OriginReviewSessionID pgtype.UUID `json:"origin_review_session_id"`
	OriginHeadBranch      string      `json:"origin_head_branch"`
}

// Queries backing SentinelFixStore (Step 48, "sentinels + suggestions",
// §17) -- see migrations/000047_sentinel_fixes.up.sql's own doc comment
// for the full table design and its two-step claim idiom.
// Step ONE of the atomic claim (mirrors github_pr_sessions' own identical
// two-step sequencing, migrations/000028's own doc comment): ON CONFLICT
// DO NOTHING ensures a row exists for (repo_full_name, origin_pr_number)
// -- callers check RowsAffected (1 = this call created the row and is
// therefore the genuine first claimant; 0 = a row already existed, from
// an earlier qualifying finding on the SAME PR) purely for logging/metrics,
// never as the actual claim decision -- GetSentinelFixForUpdate below,
// run in the SAME transaction immediately after, is what the caller
// actually branches on (whether fix_child_session_id is already set).
func (q *Queries) InsertSentinelFixIfAbsent(ctx context.Context, arg InsertSentinelFixIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSentinelFixIfAbsent,
		arg.RepoFullName,
		arg.OriginPrNumber,
		arg.OriginReviewSessionID,
		arg.OriginHeadBranch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSentinelFixAbandoned = `-- name: MarkSentinelFixAbandoned :one
UPDATE sentinel_fixes
SET status = 'abandoned', updated_at = now()
WHERE id = $1
RETURNING id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at
`

// Set when the origin PR itself is closed WITHOUT merging (§17.5: "the
// fix PR is simply left open as an ordinary review item -- never silently
// discarded") -- this row's own terminal-but-not-merged state, purely for
// observability; the fix PR itself is never touched by this transition.
func (q *Queries) MarkSentinelFixAbandoned(ctx context.Context, id pgtype.UUID) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, markSentinelFixAbandoned, id)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSentinelFixMerged = `-- name: MarkSentinelFixMerged :one
UPDATE sentinel_fixes
SET status = 'fix_merged', updated_at = now()
WHERE id = $1
RETURNING id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at
`

// Merge-gating's own terminal write (§17.4) -- status moves to
// 'fix_merged' once all four checks passed and the fix PR actually
// merged.
func (q *Queries) MarkSentinelFixMerged(ctx context.Context, id pgtype.UUID) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, markSentinelFixMerged, id)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSentinelFixChildSession = `-- name: UpdateSentinelFixChildSession :one
UPDATE sentinel_fixes
SET fix_child_session_id = $2, status = 'spawned', updated_at = now()
WHERE id = $1
RETURNING id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at
`

type UpdateSentinelFixChildSessionParams struct {
	ID                pgtype.UUID `json:"id"`
	FixChildSessionID pgtype.UUID `json:"fix_child_session_id"`
}

// Set once the outbox worker has spawned the child session (§17.2) --
// status moves from 'pending' to 'spawned'.
func (q *Queries) UpdateSentinelFixChildSession(ctx context.Context, arg UpdateSentinelFixChildSessionParams) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, updateSentinelFixChildSession, arg.ID, arg.FixChildSessionID)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSentinelFixOpened = `-- name: UpdateSentinelFixOpened :one
UPDATE sentinel_fixes
SET fix_pr_number = $2, status = 'fix_open', updated_at = now()
WHERE id = $1
RETURNING id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at
`

type UpdateSentinelFixOpenedParams struct {
	ID          pgtype.UUID `json:"id"`
	FixPrNumber *int32      `json:"fix_pr_number"`
}

// Set once pushpr.go's own createSentinelFixPRBestEffort has actually
// opened the fix PR -- status moves from 'spawned' to 'fix_open'.
func (q *Queries) UpdateSentinelFixOpened(ctx context.Context, arg UpdateSentinelFixOpenedParams) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, updateSentinelFixOpened, arg.ID, arg.FixPrNumber)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSentinelFixStackRegistered = `-- name: UpdateSentinelFixStackRegistered :one
UPDATE sentinel_fixes
SET stack_registered = $2, updated_at = now()
WHERE id = $1
RETURNING id, repo_full_name, origin_pr_number, origin_review_session_id, origin_head_branch, fix_child_session_id, fix_pr_number, status, stack_registered, created_at, updated_at
`

type UpdateSentinelFixStackRegisteredParams struct {
	ID              pgtype.UUID `json:"id"`
	StackRegistered bool        `json:"stack_registered"`
}

// Set (best-effort, §17.2/§17.6: "logged and otherwise ignored" on any
// failure) after the POST /repos/{owner}/{repo}/stacks call -- an
// observability-only column, never the authority on whether registration
// actually stuck (that authority is always a fresh GetPullRequest.Stack
// field, per §17.6 -- see this table's own migration doc comment).
func (q *Queries) UpdateSentinelFixStackRegistered(ctx context.Context, arg UpdateSentinelFixStackRegisteredParams) (SentinelFix, error) {
	row := q.db.QueryRow(ctx, updateSentinelFixStackRegistered, arg.ID, arg.StackRegistered)
	var i SentinelFix
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.OriginPrNumber,
		&i.OriginReviewSessionID,
		&i.OriginHeadBranch,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.Status,
		&i.StackRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
