// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title, spawn_source, created_by)
VALUES ($1, $2, $3)
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at
`

type CreateSessionParams struct {
	Title       *string            `json:"title"`
	SpawnSource SessionSpawnSource `json:"spawn_source"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

// Queries backing SessionStore (§4.3). Just enough to prove the pipeline
// end to end (create + get) — full CRUD lands with the PRs that build out
// session-actor persistence (PR-11+).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Title, arg.SpawnSource, arg.CreatedBy)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
