// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpActorEpoch = `-- name: BumpActorEpoch :one
UPDATE sessions SET actor_epoch = actor_epoch + 1
WHERE id = $1
RETURNING actor_epoch
`

// Increments a session's actor_epoch and returns the new value. Called
// once, at acquisition time, when an actor takes ownership of a session
// (§2: "bumped on each acquisition") -- never as part of an ordinary
// state-transition write (those only READ the epoch, via
// GetSessionActorEpochForUpdate below, to check it hasn't moved).
func (q *Queries) BumpActorEpoch(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpActorEpoch, id)
	var actor_epoch int64
	err := row.Scan(&actor_epoch)
	return actor_epoch, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title, spawn_source, created_by, repos, environment_id, provenance_tag, build_model_id)
VALUES ($1, $2, $3, COALESCE($4, '[]'::jsonb), $5, $6, $7)
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id
`

type CreateSessionParams struct {
	Title         *string            `json:"title"`
	SpawnSource   SessionSpawnSource `json:"spawn_source"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	Repos         interface{}        `json:"repos"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	ProvenanceTag *string            `json:"provenance_tag"`
	BuildModelID  *string            `json:"build_model_id"`
}

// Queries backing SessionStore (§4.3). Just enough to prove the pipeline
// end to end (create + get) — full CRUD lands with the PRs that build out
// session-actor persistence (PR-11+).
// repos defaults to '[]'::jsonb via COALESCE (not the column's own DEFAULT
// clause) specifically so every EXISTING call site that never set Repos
// (every session created before Step 21 "e2e happy path") keeps compiling
// and behaving identically: a nil/absent []byte param binds SQL NULL, and
// COALESCE(NULL, '[]'::jsonb) resolves to the same empty-list default a
// bare column-default insert would have produced.
//
// environment_id/provenance_tag (row 10, "domain: Environment scoping",
// §14.1) are both sqlc.narg -- nullable, optional params -- so every
// EXISTING call site that never sets them (every session created before
// this batch) keeps compiling and behaving identically: both stay NULL,
// byte-for-byte today's unscoped behavior.
//
// build_model_id (Step 37, "plan mode, web", §12.2 item 3) is likewise
// sqlc.narg -- every EXISTING call site that never sets it keeps
// compiling and behaving identically (NULL, "use the default model
// catalog entry", migrations/000034_plan_mode.up.sql's own convention).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Title,
		arg.SpawnSource,
		arg.CreatedBy,
		arg.Repos,
		arg.EnvironmentID,
		arg.ProvenanceTag,
		arg.BuildModelID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
	)
	return i, err
}

const getSessionActorEpochForUpdate = `-- name: GetSessionActorEpochForUpdate :one
SELECT actor_epoch FROM sessions
WHERE id = $1
FOR UPDATE
`

// Locks and reads a session's current actor_epoch. Called at the START of
// every transactional write, inside that same transaction, to fence a
// stale writer (an actor whose epoch no longer matches -- proof a newer
// actor has since taken over) before it does anything else (§2: "writes
// with a stale epoch fail").
func (q *Queries) GetSessionActorEpochForUpdate(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionActorEpochForUpdate, id)
	var actor_epoch int64
	err := row.Scan(&actor_epoch)
	return actor_epoch, err
}

const updateSessionConversationID = `-- name: UpdateSessionConversationID :one
UPDATE sessions
SET opencode_conversation_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id
`

type UpdateSessionConversationIDParams struct {
	ID                     pgtype.UUID `json:"id"`
	OpencodeConversationID *string     `json:"opencode_conversation_id"`
}

// Persists the session-level OpenCode conversation id (§3.3: "recorded at
// turn start ... also reported on every heartbeat"; see
// migrations/000018_session_repos.up.sql's own doc comment for why this is
// session-scoped, not turns.conversation_id). Called by
// internal/app/sessionactor's handleSandboxEvent whenever a "heartbeat"
// event carries a non-nil ConversationId.
func (q *Queries) UpdateSessionConversationID(ctx context.Context, arg UpdateSessionConversationIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionConversationID, arg.ID, arg.OpencodeConversationID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
	)
	return i, err
}

const updateSessionIntentDecisionIfNull = `-- name: UpdateSessionIntentDecisionIfNull :execrows
UPDATE sessions
SET intent_decision = $2
WHERE id = $1 AND intent_decision IS NULL
`

type UpdateSessionIntentDecisionIfNullParams struct {
	ID             pgtype.UUID `json:"id"`
	IntentDecision []byte      `json:"intent_decision"`
}

// Step 36's ("intent classifier", §18.4) write-once guarded update:
// "UPDATE sessions SET intent_decision = ... WHERE intent_decision IS
// NULL" -- NOT read-then-write, first decision wins, no application-level
// lock needed. RowsAffected (via :execrows) is the caller's own win/lose
// signal: 1 means THIS call actually set intent_decision (first writer
// wins); 0 means some other writer already set it first -- internal/app/
// intentclassifier's persistence path treats either outcome as success,
// never an error, since "someone already recorded a decision for this
// session" is exactly the expected, race-safe steady state, not a
// failure.
func (q *Queries) UpdateSessionIntentDecisionIfNull(ctx context.Context, arg UpdateSessionIntentDecisionIfNullParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionIntentDecisionIfNull, arg.ID, arg.IntentDecision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status = $2, failure_reason = $3, updated_at = now()
WHERE id = $1
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id
`

type UpdateSessionStatusParams struct {
	ID            pgtype.UUID           `json:"id"`
	Status        SessionStatus         `json:"status"`
	FailureReason *SessionFailureReason `json:"failure_reason"`
}

// Persists a session's derived status + failure_reason --
// internal/domain/session.DeriveStatus's output, never written directly
// (§11: "every state transition goes through the machine's transition
// table").
func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status, arg.FailureReason)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
	)
	return i, err
}
