// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shadowscmwrites.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShadowSCMWrite = `-- name: CreateShadowSCMWrite :one
INSERT INTO shadow_scm_writes (
    operation, repo_full_name, target, spec_json, result_json, session_id, correlation_id, heavy_content
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, operation, repo_full_name, target, spec_json, result_json, session_id, correlation_id, created_at, heavy_content
`

type CreateShadowSCMWriteParams struct {
	Operation     string      `json:"operation"`
	RepoFullName  string      `json:"repo_full_name"`
	Target        *string     `json:"target"`
	SpecJson      []byte      `json:"spec_json"`
	ResultJson    []byte      `json:"result_json"`
	SessionID     pgtype.UUID `json:"session_id"`
	CorrelationID *string     `json:"correlation_id"`
	HeavyContent  *string     `json:"heavy_content"`
}

// §30.6's record-or-fail insert: the gate returns success to its caller
// ONLY if this commits. A suppressed-but-unrecorded effect is a contract
// violation, and failing loudly is safe -- nothing external happened, so
// there is nothing to reconcile.
//
// heavy_content (migrations/000110_shadow_scm_writes_heavy_content.up.sql)
// is NULL for every operation except update_file_content -- see that
// migration's own doc comment, and shadowledger.Record (writer.go),
// the one call site that ever passes a non-NULL value here.
func (q *Queries) CreateShadowSCMWrite(ctx context.Context, arg CreateShadowSCMWriteParams) (ShadowScmWrite, error) {
	row := q.db.QueryRow(ctx, createShadowSCMWrite,
		arg.Operation,
		arg.RepoFullName,
		arg.Target,
		arg.SpecJson,
		arg.ResultJson,
		arg.SessionID,
		arg.CorrelationID,
		arg.HeavyContent,
	)
	var i ShadowScmWrite
	err := row.Scan(
		&i.ID,
		&i.Operation,
		&i.RepoFullName,
		&i.Target,
		&i.SpecJson,
		&i.ResultJson,
		&i.SessionID,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.HeavyContent,
	)
	return i, err
}

const listShadowSCMWritesForRepo = `-- name: ListShadowSCMWritesForRepo :many
SELECT id, operation, repo_full_name, target, spec_json, result_json, session_id, correlation_id, created_at, heavy_content FROM shadow_scm_writes
WHERE repo_full_name = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListShadowSCMWritesForRepoParams struct {
	RepoFullName string `json:"repo_full_name"`
	Limit        int32  `json:"limit"`
}

// Newest first, the order the operator surface reads them in.
func (q *Queries) ListShadowSCMWritesForRepo(ctx context.Context, arg ListShadowSCMWritesForRepoParams) ([]ShadowScmWrite, error) {
	rows, err := q.db.Query(ctx, listShadowSCMWritesForRepo, arg.RepoFullName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShadowScmWrite
	for rows.Next() {
		var i ShadowScmWrite
		if err := rows.Scan(
			&i.ID,
			&i.Operation,
			&i.RepoFullName,
			&i.Target,
			&i.SpecJson,
			&i.ResultJson,
			&i.SessionID,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.HeavyContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
