// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one

INSERT INTO turns (session_id, status, prompt, model_id, plan_mode)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, status, conversation_id, created_at, dispatched_at, completed_at, prompt, model_id, plan_mode, dispatched_sandbox_gen, progress_notified_at
`

type CreateTurnParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Status    TurnStatus  `json:"status"`
	Prompt    *string     `json:"prompt"`
	ModelID   *string     `json:"model_id"`
	PlanMode  bool        `json:"plan_mode"`
}

// Queries backing TurnStore (§4.3). Just enough to prove the pipeline end
// to end (create + get), including exercising the
// turns_one_processing_per_session partial unique index (§3.3).
// prompt/model_id/plan_mode (migrations/000018_session_repos.up.sql, Step
// 21) are the turn's own dispatch-time inputs -- prompt/model_id are
// nullable and plan_mode defaults false, so every EXISTING call site
// (every prior Step's `CreateTurnParams{SessionID, Status}`) keeps
// compiling and behaving identically: the zero-value nil/nil/false it
// already implicitly got before this Step's own columns existed.
func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.SessionID,
		arg.Status,
		arg.Prompt,
		arg.ModelID,
		arg.PlanMode,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Prompt,
		&i.ModelID,
		&i.PlanMode,
		&i.DispatchedSandboxGen,
		&i.ProgressNotifiedAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, session_id, status, conversation_id, created_at, dispatched_at, completed_at, prompt, model_id, plan_mode, dispatched_sandbox_gen, progress_notified_at FROM turns
WHERE id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Prompt,
		&i.ModelID,
		&i.PlanMode,
		&i.DispatchedSandboxGen,
		&i.ProgressNotifiedAt,
	)
	return i, err
}

const listTurnsForSession = `-- name: ListTurnsForSession :many
SELECT id, session_id, status, conversation_id, created_at, dispatched_at, completed_at, prompt, model_id, plan_mode, dispatched_sandbox_gen, progress_notified_at FROM turns
WHERE session_id = $1
ORDER BY created_at ASC
`

// Full turn history for one session, oldest first -- exactly the input
// shape internal/domain/session.DeriveStatus requires (an ordered slice
// of turn.Summary derived from these rows).
func (q *Queries) ListTurnsForSession(ctx context.Context, sessionID pgtype.UUID) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listTurnsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Status,
			&i.ConversationID,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.Prompt,
			&i.ModelID,
			&i.PlanMode,
			&i.DispatchedSandboxGen,
			&i.ProgressNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTurnProgressNotified = `-- name: MarkTurnProgressNotified :execrows
UPDATE turns
SET progress_notified_at = $2
WHERE id = $1 AND progress_notified_at IS NULL
`

type MarkTurnProgressNotifiedParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ProgressNotifiedAt pgtype.Timestamptz `json:"progress_notified_at"`
}

// Audit finding M16 ("completeness", internal/adapters/outbound/linearapi/
// doc.go): atomic, race-safe "has this turn already had its one mid-turn
// progress milestone fired" guard -- mirrors ApprovePlanIfAwaitingApproval/
// RejectPlanIfAwaitingApproval's own "guarded UPDATE, observed via
// :execrows" idiom exactly (queries/plans.sql), just for a nullable
// timestamp rather than an enum status. 0 rows affected means
// progress_notified_at was already set for this turn (a second, later
// tool_call event in the same turn -- the expected, common case once the
// milestone has already fired once -- or a race); exactly 1 row affected
// means THIS call is the one that gets to enqueue the Linear progress
// notification (see internal/app/sessionactor/progressnotify.go).
func (q *Queries) MarkTurnProgressNotified(ctx context.Context, arg MarkTurnProgressNotifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTurnProgressNotified, arg.ID, arg.ProgressNotifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTurnStatus = `-- name: UpdateTurnStatus :one
UPDATE turns
SET status = $2,
    dispatched_at = COALESCE($3, dispatched_at),
    completed_at = COALESCE($4, completed_at),
    dispatched_sandbox_gen = COALESCE($5, dispatched_sandbox_gen)
WHERE id = $1
RETURNING id, session_id, status, conversation_id, created_at, dispatched_at, completed_at, prompt, model_id, plan_mode, dispatched_sandbox_gen, progress_notified_at
`

type UpdateTurnStatusParams struct {
	ID                   pgtype.UUID        `json:"id"`
	Status               TurnStatus         `json:"status"`
	DispatchedAt         pgtype.Timestamptz `json:"dispatched_at"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	DispatchedSandboxGen *int32             `json:"dispatched_sandbox_gen"`
}

// Sets a turn's status, plus dispatched_at/completed_at/
// dispatched_sandbox_gen when the caller supplies one (sqlc.narg +
// COALESCE: an absent/NULL argument leaves the existing column value
// untouched, matching dispatched_at/completed_at's own nullability --
// each is set at most once, at the (from, trigger) transition that
// reaches Dispatched or a terminal state respectively).
//
// dispatched_sandbox_gen (migration 000026_turn_dispatch_gen.up.sql, Step
// 28 "turn recovery") is stamped by TWO distinct call sites sharing this
// SAME query, both at the moment a Prompt payload is built and about to be
// sent: tryPlanDispatch (internal/app/sessionactor/dispatch.go), alongside
// the SAME status=dispatched write that already sets dispatched_at, for
// the normal Pending->Dispatched->Processing path; and tryPlanReenqueue
// (same file), which passes the CURRENT status back unchanged (the turn
// is already, validly, Processing -- this call re-stamps
// dispatched_sandbox_gen only, never re-transitions status) for a
// Processing turn whose prompt needs re-sending to a respawned sandbox
// incarnation.
func (q *Queries) UpdateTurnStatus(ctx context.Context, arg UpdateTurnStatusParams) (Turn, error) {
	row := q.db.QueryRow(ctx, updateTurnStatus,
		arg.ID,
		arg.Status,
		arg.DispatchedAt,
		arg.CompletedAt,
		arg.DispatchedSandboxGen,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Prompt,
		&i.ModelID,
		&i.PlanMode,
		&i.DispatchedSandboxGen,
		&i.ProgressNotifiedAt,
	)
	return i, err
}
