// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one

INSERT INTO turns (session_id, status)
VALUES ($1, $2)
RETURNING id, session_id, status, conversation_id, created_at, dispatched_at, completed_at
`

type CreateTurnParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Status    TurnStatus  `json:"status"`
}

// Queries backing TurnStore (§4.3). Just enough to prove the pipeline end
// to end (create + get), including exercising the
// turns_one_processing_per_session partial unique index (§3.3).
func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn, arg.SessionID, arg.Status)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, session_id, status, conversation_id, created_at, dispatched_at, completed_at FROM turns
WHERE id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Status,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.CompletedAt,
	)
	return i, err
}
