// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one

INSERT INTO user_sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateUserSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing UserSessionStore (§13.1's own backend-issued cookie
// session mechanism, migrations/000017_auth_v1.up.sql). CreateUserSession
// mints a fresh row -- the plaintext token itself, and hashing it, are the
// caller's own job (internal/platform.GenerateToken / HashToken, reused
// unchanged from Step 19's ws-token mechanism), this query only ever sees
// the already-hashed value. GetUserSessionByHash is the auth middleware's
// own verify-by-hash lookup on every gated request.
// DeleteUserSession is logout's own real revocation -- a genuine DELETE,
// not merely clearing the browser's cookie.
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions
WHERE id = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSession, id)
	return err
}

const getUserSessionByHash = `-- name: GetUserSessionByHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM user_sessions
WHERE token_hash = $1
`

func (q *Queries) GetUserSessionByHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
