// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (primary_email, display_name, role)
VALUES ($1, $2, $3)
RETURNING id, primary_email, display_name, role, disabled, created_at
`

type CreateUserParams struct {
	PrimaryEmail string   `json:"primary_email"`
	DisplayName  string   `json:"display_name"`
	Role         UserRole `json:"role"`
}

// Queries backing UserStore (§13.2 identity graph anchor, §13.3 RBAC role,
// migrations/000002_users.up.sql). CreateUser inserts a user row once, at
// first-sign-in creation time (internal/adapters/inbound/auth's own OAuth
// callback handler) -- role is set once, at creation, per that handler's
// own initial-admin logic. GetUserByID backs both the callback handler and
// the auth middleware's own per-request lookup.
//
// Step 39 ("identities + full RBAC", §13.2/§13.3) additions --
// ListUsersOrderedByCreatedAt/UpdateUserRole/GetUserByPrimaryEmail back the
// members API (internal/adapters/inbound/httpapi/members.go) and the
// auto-link algorithm's own email-match step
// (internal/app/identitylink.Resolve): the ONLY writes to an existing
// user's own row this codebase makes past creation time.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PrimaryEmail, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, primary_email, display_name, role, disabled, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPrimaryEmail = `-- name: GetUserByPrimaryEmail :one
SELECT id, primary_email, display_name, role, disabled, created_at FROM users
WHERE lower(primary_email) = lower($1)
`

// Case-insensitive: email addresses are conventionally
// case-insensitive (at least in the local-part-plus-domain sense every
// real mail provider actually applies), and this is ONLY ever compared
// against an email another provider (GitHub/Slack/Linear) already
// independently attests to, never user-supplied free text -- matching
// lower(email) on both sides is the same convention
// ListVerifiedIdentityUserIDsByEmail (identities.sql) uses for its own
// verified-identity-email match, so the two halves of §13.2's own "match
// against primary_email AND verified identity emails" never disagree on
// case sensitivity.
func (q *Queries) GetUserByPrimaryEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPrimaryEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAdminIDsForUpdate = `-- name: ListActiveAdminIDsForUpdate :many

SELECT id FROM users
WHERE role = 'admin' AND disabled = false
FOR UPDATE
`

// An audit finding (H8) confirmed UpdateMemberRole had no protection
// against demoting the last remaining admin: doing so permanently locks
// the deployment out of every admin-only endpoint, including role
// management itself, with no recovery path short of direct DB surgery.
// ListActiveAdminIDsForUpdate is that guard's own query -- FOR UPDATE
// (not a plain count) so it locks every currently-qualifying row: a
// SECOND concurrent demotion of a DIFFERENT admin, running this SAME
// query inside its own transaction, blocks here until the first
// transaction commits or rolls back, then re-evaluates against the
// now-current row versions (Postgres' own read-committed row-locking
// semantics) rather than both transactions reading a stale "2 admins"
// snapshot and both proceeding.
func (q *Queries) ListActiveAdminIDsForUpdate(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveAdminIDsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersOrderedByCreatedAt = `-- name: ListUsersOrderedByCreatedAt :many
SELECT id, primary_email, display_name, role, disabled, created_at FROM users
ORDER BY created_at ASC
`

// Backs GET /api/members -- every user, oldest-first (matches
// ListSummariesForSession's own "stable, predictable order" precedent
// elsewhere in this codebase; oldest-first reads naturally as "founding
// members first").
func (q *Queries) ListUsersOrderedByCreatedAt(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersOrderedByCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryEmail,
			&i.DisplayName,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, primary_email, display_name, role, disabled, created_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role UserRole    `json:"role"`
}

// Backs the admin-only role-change endpoint (§13.3's own "members & roles:
// admin only" row) -- the ONLY column of an existing user's row this
// codebase ever mutates past creation time.
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}
