// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (primary_email, display_name, role)
VALUES ($1, $2, $3)
RETURNING id, primary_email, display_name, role, disabled, created_at
`

type CreateUserParams struct {
	PrimaryEmail string   `json:"primary_email"`
	DisplayName  string   `json:"display_name"`
	Role         UserRole `json:"role"`
}

// Queries backing UserStore (§13.2 identity graph anchor, §13.3 RBAC role,
// migrations/000002_users.up.sql). CreateUser inserts a user row once, at
// first-sign-in creation time (internal/adapters/inbound/auth's own OAuth
// callback handler) -- role is set once, at creation, per that handler's
// own initial-admin logic; no Update/List exists yet because nothing
// changes a user's own row after creation in this Step (role/disabled
// editing is Step 39's "members API" job). GetUserByID backs both the
// callback handler and the auth middleware's own per-request lookup.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PrimaryEmail, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, primary_email, display_name, role, disabled, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}
