// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhookdeliveries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDelivery = `-- name: ClaimWebhookDelivery :one

INSERT INTO webhook_deliveries (provider, delivery_id) VALUES ($1, $2)
ON CONFLICT (provider, delivery_id) DO UPDATE SET received_at = webhook_deliveries.received_at
RETURNING provider, delivery_id, received_at, (xmax = 0) AS inserted
`

type ClaimWebhookDeliveryParams struct {
	Provider   string `json:"provider"`
	DeliveryID string `json:"delivery_id"`
}

type ClaimWebhookDeliveryRow struct {
	Provider   string             `json:"provider"`
	DeliveryID string             `json:"delivery_id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	Inserted   bool               `json:"inserted"`
}

// Queries backing WebhookDeliveryStore (§5.1's dedupe/coalescing claim,
// §4.3). No caller exists yet -- Steps 32/33/34 (GitHub/Slack/Linear
// ingress) are the ones that actually call ClaimWebhookDelivery, once
// each provider's own adapter has verified its signature and parsed out
// its own delivery id.
// Atomic first-writer-wins claim on (provider, delivery_id) -- the SAME
// "(xmax = 0) AS inserted" idiom postgres/queries/events.sql's own
// CreateEvent already establishes: a deliberate, self-referential no-op
// update (received_at is set back to its own current value) so RETURNING
// always yields exactly one row whether this call just inserted a fresh
// row or found an already-claimed one from an earlier delivery of the
// SAME (provider, delivery_id) -- a real webhook redelivery, which every
// provider this table serves does on a timeout/5xx. Callers branch on
// Inserted: true means "process this delivery", false means "already
// claimed/processed -- skip, never double-act on a resend".
func (q *Queries) ClaimWebhookDelivery(ctx context.Context, arg ClaimWebhookDeliveryParams) (ClaimWebhookDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimWebhookDelivery, arg.Provider, arg.DeliveryID)
	var i ClaimWebhookDeliveryRow
	err := row.Scan(
		&i.Provider,
		&i.DeliveryID,
		&i.ReceivedAt,
		&i.Inserted,
	)
	return i, err
}

const releaseWebhookDelivery = `-- name: ReleaseWebhookDelivery :exec
DELETE FROM webhook_deliveries WHERE provider = $1 AND delivery_id = $2
`

type ReleaseWebhookDeliveryParams struct {
	Provider   string `json:"provider"`
	DeliveryID string `json:"delivery_id"`
}

// Un-claims a (provider, delivery_id) this same request just claimed via
// ClaimWebhookDelivery, but failed to actually process (payload parse
// error, transient DB error downstream of the claim, etc.) -- called ONLY
// on those genuine-failure paths, never on a legitimate "nothing to do"
// outcome. Without this, a claim that wins the INSERT but then fails
// before the work it gates ever completes would permanently poison that
// (provider, delivery_id): every subsequent redelivery (which every one
// of these providers sends on a timeout/5xx -- the exact scenario a
// mid-pipeline failure often causes) would see Inserted=false and skip
// reprocessing forever, silently dropping the event. Deleting the row
// lets the next redelivery re-claim and retry from scratch.
func (q *Queries) ReleaseWebhookDelivery(ctx context.Context, arg ReleaseWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, releaseWebhookDelivery, arg.Provider, arg.DeliveryID)
	return err
}
