// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTurnToWorkflowStepRun = `-- name: AttachTurnToWorkflowStepRun :exec
UPDATE workflow_step_runs SET turn_id = $2, updated_at = now() WHERE id = $1
`

type AttachTurnToWorkflowStepRunParams struct {
	ID     pgtype.UUID `json:"id"`
	TurnID pgtype.UUID `json:"turn_id"`
}

func (q *Queries) AttachTurnToWorkflowStepRun(ctx context.Context, arg AttachTurnToWorkflowStepRunParams) error {
	_, err := q.db.Exec(ctx, attachTurnToWorkflowStepRun, arg.ID, arg.TurnID)
	return err
}

const claimWorkflowRunEscalationNotice = `-- name: ClaimWorkflowRunEscalationNotice :execrows
UPDATE workflow_runs SET needs_review_notified_at = now(), updated_at = now() WHERE id = $1 AND needs_review_notified_at IS NULL
`

// The §25.9/§24.6-mirroring "one notice, never repeated" claim
// (migrations/000058_workflow_hitl.up.sql's own doc comment): guarded on
// needs_review_notified_at IS NULL, so of any number of concurrent/
// repeated attempts to escalate the SAME run, exactly one ever claims the
// right to enqueue the notice -- :execrows lets the caller tell "I claimed
// it, send the notice" (1) from "already claimed/sent by an earlier
// escalation" (0) apart, without a separate existence check.
func (q *Queries) ClaimWorkflowRunEscalationNotice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimWorkflowRunEscalationNotice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWorkflowRun = `-- name: CompleteWorkflowRun :one
UPDATE workflow_runs SET status = 'completed', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

func (q *Queries) CompleteWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, completeWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const countWorkflowStepRunsForStepDefinition = `-- name: CountWorkflowStepRunsForStepDefinition :one
SELECT COUNT(*) FROM workflow_step_runs WHERE workflow_run_id = $1 AND step_definition_id = $2
`

type CountWorkflowStepRunsForStepDefinitionParams struct {
	WorkflowRunID    pgtype.UUID `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID `json:"step_definition_id"`
}

// §25.5's own "iteration count reads COUNT(*) on workflow_step_runs, no
// dedicated counter column" -- scoped to ONE run (a count is never summed
// across a session's separate runs) and ONE step definition (the step
// about to receive a new attempt). The engine consults this ONLY when a
// needs_fix edge is about to advance to a step that might already have
// prior attempts in THIS run -- see internal/app/workflowengine's own
// advance.go for the exact call site and the "count > 0 means a genuine
// re-fire" reasoning.
func (q *Queries) CountWorkflowStepRunsForStepDefinition(ctx context.Context, arg CountWorkflowStepRunsForStepDefinitionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowStepRunsForStepDefinition, arg.WorkflowRunID, arg.StepDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (session_id, lane, workflow_definition_id, definition_version)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

type CreateWorkflowRunParams struct {
	SessionID            pgtype.UUID  `json:"session_id"`
	Lane                 WorkflowLane `json:"lane"`
	WorkflowDefinitionID pgtype.UUID  `json:"workflow_definition_id"`
	DefinitionVersion    int32        `json:"definition_version"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.SessionID,
		arg.Lane,
		arg.WorkflowDefinitionID,
		arg.DefinitionVersion,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const createWorkflowStepRun = `-- name: CreateWorkflowStepRun :one
INSERT INTO workflow_step_runs (workflow_run_id, step_definition_id)
VALUES ($1, $2)
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type CreateWorkflowStepRunParams struct {
	WorkflowRunID    pgtype.UUID `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID `json:"step_definition_id"`
}

func (q *Queries) CreateWorkflowStepRun(ctx context.Context, arg CreateWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepRun, arg.WorkflowRunID, arg.StepDefinitionID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const decideWorkflowStepRunApprove = `-- name: DecideWorkflowStepRunApprove :execrows

UPDATE workflow_step_runs
SET status = 'completed', decision = 'approve', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunApproveParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

// DecideWorkflowStepRunApprove/Reject/Revise are three narrow,
// single-purpose guarded UPDATEs -- mirroring plans.sql's own
// ApprovePlanIfAwaitingApproval/RejectPlanIfAwaitingApproval precedent
// (two verdicts, two statements) exactly, extended to three here so which
// resulting status/decision applies to which verdict is enforced by WHICH
// STATEMENT RUNS, never by a conditional expression a future edit could
// silently get wrong (this file's own header comment states this
// discipline for MarkWorkflowStepRunAwaitingDecision/FinishWorkflowStepRun
// above; the same reasoning applies here). All three share the identical
// "AND status = 'awaiting_decision'" guard -- :execrows lets the handler
// distinguish "this call won the decision" from "already decided (or a
// stale id)" without a separate existence check, exactly like
// ApprovePlanIfAwaitingApproval's own :execrows shape. decisionText ($2)
// is nullable: NULL for approve (ignored), optional context for reject,
// required non-empty for revise (enforced at the application layer, per
// WorkflowStepDecideRequest.text's own schema doc comment).
//
// Resulting status: approve/revise both land on 'completed' (the
// attempt's own execution genuinely finished either way -- what happens
// NEXT, advance vs re-execute, is the decision column's own job, not the
// status column's); reject lands on 'failed', mirroring
// WorkflowStepDecideResponse.runStatus's own documented "'failed' after a
// winning reject ends the run" example -- the owning run's and the
// decided attempt's own resulting status agree by construction.
func (q *Queries) DecideWorkflowStepRunApprove(ctx context.Context, arg DecideWorkflowStepRunApproveParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunApprove, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decideWorkflowStepRunReject = `-- name: DecideWorkflowStepRunReject :execrows
UPDATE workflow_step_runs
SET status = 'failed', decision = 'reject', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunRejectParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

func (q *Queries) DecideWorkflowStepRunReject(ctx context.Context, arg DecideWorkflowStepRunRejectParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunReject, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decideWorkflowStepRunRevise = `-- name: DecideWorkflowStepRunRevise :execrows
UPDATE workflow_step_runs
SET status = 'completed', decision = 'revise', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunReviseParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

func (q *Queries) DecideWorkflowStepRunRevise(ctx context.Context, arg DecideWorkflowStepRunReviseParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunRevise, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const escalateWorkflowRun = `-- name: EscalateWorkflowRun :one
UPDATE workflow_runs SET status = 'needs_review', updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

func (q *Queries) EscalateWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, escalateWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const failWorkflowRun = `-- name: FailWorkflowRun :one
UPDATE workflow_runs SET status = 'failed', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

// Step 56's own addition (§25.9): a winning HITL reject verdict ends the
// run -- mirrors CompleteWorkflowRun's own shape exactly, landing on
// 'failed' instead of 'completed' (WorkflowStepDecideResponse.runStatus's
// own documented "'failed' after a winning reject ends the run" example).
// Terminal (finished_at set), unlike EscalateWorkflowRun's own
// 'needs_review' (non-terminal, waiting on a human) -- a reject is itself
// the human's own final word, nothing further to wait on.
func (q *Queries) FailWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, failWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const finishWorkflowStepRun = `-- name: FinishWorkflowStepRun :one
UPDATE workflow_step_runs
SET status = $2, outcome_status = COALESCE(outcome_status, $3), finished_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type FinishWorkflowStepRunParams struct {
	ID            pgtype.UUID                `json:"id"`
	Status        WorkflowStepRunStatus      `json:"status"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

// status is the caller-computed terminal workflow_step_run_status
// (completed/failed/cancelled -- never awaiting_decision, which
// MarkWorkflowStepRunAwaitingDecision above owns exclusively).
func (q *Queries) FinishWorkflowStepRun(ctx context.Context, arg FinishWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, finishWorkflowStepRun, arg.ID, arg.Status, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGlobalWorkflowBinding = `-- name: GetGlobalWorkflowBinding :one
SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name IS NULL
`

func (q *Queries) GetGlobalWorkflowBinding(ctx context.Context, lane WorkflowLane) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getGlobalWorkflowBinding, lane)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunByTurnID = `-- name: GetLiveWorkflowStepRunByTurnID :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs WHERE turn_id = $1 AND status = 'running'
`

func (q *Queries) GetLiveWorkflowStepRunByTurnID(ctx context.Context, turnID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunByTurnID, turnID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunForRun = `-- name: GetLiveWorkflowStepRunForRun :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs
WHERE workflow_run_id = $1 AND status IN ('running', 'awaiting_decision')
`

func (q *Queries) GetLiveWorkflowStepRunForRun(ctx context.Context, workflowRunID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunForRun, workflowRunID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunningWorkflowRunForSession = `-- name: GetRunningWorkflowRunForSession :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at FROM workflow_runs WHERE session_id = $1 AND status = 'running'
`

func (q *Queries) GetRunningWorkflowRunForSession(ctx context.Context, sessionID pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getRunningWorkflowRunForSession, sessionID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const getWorkflowBindingForRepo = `-- name: GetWorkflowBindingForRepo :one

SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name = $2
`

type GetWorkflowBindingForRepoParams struct {
	Lane         WorkflowLane `json:"lane"`
	RepoFullName *string      `json:"repo_full_name"`
}

// Queries backing WorkflowStore (Step 55, "workflow execution engine",
// §25.6/§25.7/§25.8), the first real reader/writer of Step 54's own dark
// schema (migrations/000057_workflows.up.sql). internal/app/workflowengine
// is this file's only caller: it resolves which (lane, repo) binding and
// WorkflowDefinition govern a session's current turn, tracks the run/
// step-run ledger these queries persist, and consults
// internal/domain/workflow.NextStep on every posted/derived step outcome
// -- never reimplementing that decision here.
//
// Binding resolution (§25.4): a repo-specific row (GetWorkflowBindingForRepo)
// always wins when one exists; GetGlobalWorkflowBinding is the guaranteed
// fallback (seeded by migration 000057 for every lane, so this SELECT is
// never truly expected to return zero rows in a correctly-migrated
// database -- see workflowengine's own fail-open handling for the
// defensive case where it somehow does).
//
// Definition assembly (GetWorkflowDefinition + ListWorkflowStepDefinitions +
// ListWorkflowEdgesForDefinition): three queries, not one join, mirroring
// domain/workflow.Definition's own shape (a definition row plus its
// ordered steps, each carrying its own outgoing edges) -- workflowengine
// groups edges by from_step_id in Go when assembling the domain value, the
// same "read plain rows, assemble the domain type in the app layer" split
// every other store in this package already follows (e.g. PlanStore never
// constructs an internal/domain/plan value itself).
//
// Run/step-run lifecycle (§25.6, migration 000057's own header comment):
// GetRunningWorkflowRunForSession/GetLiveWorkflowStepRunForRun back the
// "is there already a live run/step for this session" check
// ResolveStepForNewTurn makes before ever starting a new run --
// workflow_runs_one_running_per_session/workflow_step_runs_one_live_per_run
// (migration 000057) make violating either a live constraint violation,
// not just an application bug; this store's own CreateWorkflowRun/
// CreateWorkflowStepRun are therefore only ever called from the branch that
// already confirmed no live one exists. AttachTurnToWorkflowStepRun
// backfills turn_id once the actual turn row exists (it cannot exist before
// the step-run row is created, since ResolveStepForNewTurn must decide the
// step BEFORE the turn insert it feeds prompt/model into) --
// GetLiveWorkflowStepRunByTurnID is completion.go's own reverse lookup, at
// turn-completion time.
//
// MarkWorkflowStepRunAwaitingDecision/FinishWorkflowStepRun/
// CompleteWorkflowRun/EscalateWorkflowRun are deliberately four narrow,
// single-purpose statements rather than one CASE-parameterized UPDATE each
// -- mirroring plans.sql's own ApprovePlanIfAwaitingApproval/
// RejectPlanIfAwaitingApproval precedent (two verdicts, two statements) --
// so finished_at's own "null while awaiting_decision" invariant
// (migration 000057's own doc comment) is enforced by which statement runs,
// never by a conditional expression a future edit could silently get wrong.
// outcome_status uses COALESCE in both step-run UPDATEs so an outcome
// ALREADY posted via the step-outcome tool (SetWorkflowStepRunOutcome
// below) is never clobbered by the engine's own implicit-from-trigger
// derivation at turn-completion time -- the posted value always wins.
//
// SetWorkflowStepRunOutcome is the generic step-outcome-posting tool's own
// write (§25.6's typed {status, summary, structuredPayload} handoff,
// structurally mirroring internal/domain/reviewpost's existing
// verdict-posting shape): guarded to "AND status = 'running'" so a caller
// can only ever post onto the attempt currently actually in flight, never
// an already-finished or awaiting-decision one -- :execrows lets the
// handler distinguish "posted" from "no live attempt to post onto" without
// a separate existence check.
func (q *Queries) GetWorkflowBindingForRepo(ctx context.Context, arg GetWorkflowBindingForRepoParams) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getWorkflowBindingForRepo, arg.Lane, arg.RepoFullName)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT id, lane, name, is_built_in, version, created_at, updated_at FROM workflow_definitions WHERE id = $1
`

func (q *Queries) GetWorkflowDefinition(ctx context.Context, id pgtype.UUID) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, id)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const getWorkflowStepRun = `-- name: GetWorkflowStepRun :one

SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs WHERE id = $1
`

// Step 56 ("workflow HITL gate + circuit breaker", §25.9) own additions
// below: the decide endpoint's lookup/guarded-decision queries, the
// circuit breaker's own COUNT(*) attempt read (§25.5), and the escalation
// notice's one-time claim (migrations/000058_workflow_hitl.up.sql).
// Plain lookup by id -- the decide endpoint's own first read (mirrors
// plans.Get's identical role in decideplan.go): used both to resolve the
// target attempt before deciding it and, after the guarded UPDATE below,
// to re-fetch its REAL current state either way (won or already decided),
// exactly like DecidePlanOnTx's own plans.Get re-fetch.
func (q *Queries) GetWorkflowStepRun(ctx context.Context, id pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowStepRun, id)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listWorkflowEdgesForDefinition = `-- name: ListWorkflowEdgesForDefinition :many
SELECT id, workflow_definition_id, from_step_id, to_step_id, on_status, created_at FROM workflow_edges WHERE workflow_definition_id = $1
`

func (q *Queries) ListWorkflowEdgesForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, listWorkflowEdgesForDefinition, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEdge
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.FromStepID,
			&i.ToStepID,
			&i.OnStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepDefinitions = `-- name: ListWorkflowStepDefinitions :many
SELECT id, workflow_definition_id, step_order, kind, model_id, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position, created_at, updated_at, effort FROM workflow_step_definitions WHERE workflow_definition_id = $1 ORDER BY step_order
`

func (q *Queries) ListWorkflowStepDefinitions(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowStepDefinition, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepDefinitions, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepDefinition
	for rows.Next() {
		var i WorkflowStepDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.StepOrder,
			&i.Kind,
			&i.ModelID,
			&i.PromptTemplate,
			&i.ExecutionScope,
			&i.ConversationContinuity,
			&i.HitlBefore,
			&i.HitlAfter,
			&i.CanvasPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Effort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowStepRunAwaitingDecision = `-- name: MarkWorkflowStepRunAwaitingDecision :one
UPDATE workflow_step_runs
SET status = 'awaiting_decision', outcome_status = COALESCE(outcome_status, $2), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type MarkWorkflowStepRunAwaitingDecisionParams struct {
	ID            pgtype.UUID                `json:"id"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

func (q *Queries) MarkWorkflowStepRunAwaitingDecision(ctx context.Context, arg MarkWorkflowStepRunAwaitingDecisionParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, markWorkflowStepRunAwaitingDecision, arg.ID, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setWorkflowStepRunOutcome = `-- name: SetWorkflowStepRunOutcome :execrows
UPDATE workflow_step_runs
SET outcome_status = $2, outcome_summary = $3, outcome_payload = $4, updated_at = now()
WHERE id = $1 AND status = 'running'
`

type SetWorkflowStepRunOutcomeParams struct {
	ID             pgtype.UUID                `json:"id"`
	OutcomeStatus  *WorkflowStepOutcomeStatus `json:"outcome_status"`
	OutcomeSummary *string                    `json:"outcome_summary"`
	OutcomePayload []byte                     `json:"outcome_payload"`
}

func (q *Queries) SetWorkflowStepRunOutcome(ctx context.Context, arg SetWorkflowStepRunOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkflowStepRunOutcome,
		arg.ID,
		arg.OutcomeStatus,
		arg.OutcomeSummary,
		arg.OutcomePayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
