// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTurnToWorkflowStepRun = `-- name: AttachTurnToWorkflowStepRun :exec
UPDATE workflow_step_runs SET turn_id = $2, updated_at = now() WHERE id = $1
`

type AttachTurnToWorkflowStepRunParams struct {
	ID     pgtype.UUID `json:"id"`
	TurnID pgtype.UUID `json:"turn_id"`
}

func (q *Queries) AttachTurnToWorkflowStepRun(ctx context.Context, arg AttachTurnToWorkflowStepRunParams) error {
	_, err := q.db.Exec(ctx, attachTurnToWorkflowStepRun, arg.ID, arg.TurnID)
	return err
}

const completeWorkflowRun = `-- name: CompleteWorkflowRun :one
UPDATE workflow_runs SET status = 'completed', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at
`

func (q *Queries) CompleteWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, completeWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (session_id, lane, workflow_definition_id, definition_version)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at
`

type CreateWorkflowRunParams struct {
	SessionID            pgtype.UUID  `json:"session_id"`
	Lane                 WorkflowLane `json:"lane"`
	WorkflowDefinitionID pgtype.UUID  `json:"workflow_definition_id"`
	DefinitionVersion    int32        `json:"definition_version"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.SessionID,
		arg.Lane,
		arg.WorkflowDefinitionID,
		arg.DefinitionVersion,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createWorkflowStepRun = `-- name: CreateWorkflowStepRun :one
INSERT INTO workflow_step_runs (workflow_run_id, step_definition_id)
VALUES ($1, $2)
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type CreateWorkflowStepRunParams struct {
	WorkflowRunID    pgtype.UUID `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID `json:"step_definition_id"`
}

func (q *Queries) CreateWorkflowStepRun(ctx context.Context, arg CreateWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepRun, arg.WorkflowRunID, arg.StepDefinitionID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const escalateWorkflowRun = `-- name: EscalateWorkflowRun :one
UPDATE workflow_runs SET status = 'needs_review', updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at
`

func (q *Queries) EscalateWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, escalateWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishWorkflowStepRun = `-- name: FinishWorkflowStepRun :one
UPDATE workflow_step_runs
SET status = $2, outcome_status = COALESCE(outcome_status, $3), finished_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type FinishWorkflowStepRunParams struct {
	ID            pgtype.UUID                `json:"id"`
	Status        WorkflowStepRunStatus      `json:"status"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

// status is the caller-computed terminal workflow_step_run_status
// (completed/failed/cancelled -- never awaiting_decision, which
// MarkWorkflowStepRunAwaitingDecision above owns exclusively).
func (q *Queries) FinishWorkflowStepRun(ctx context.Context, arg FinishWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, finishWorkflowStepRun, arg.ID, arg.Status, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGlobalWorkflowBinding = `-- name: GetGlobalWorkflowBinding :one
SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name IS NULL
`

func (q *Queries) GetGlobalWorkflowBinding(ctx context.Context, lane WorkflowLane) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getGlobalWorkflowBinding, lane)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunByTurnID = `-- name: GetLiveWorkflowStepRunByTurnID :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs WHERE turn_id = $1 AND status = 'running'
`

func (q *Queries) GetLiveWorkflowStepRunByTurnID(ctx context.Context, turnID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunByTurnID, turnID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunForRun = `-- name: GetLiveWorkflowStepRunForRun :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs
WHERE workflow_run_id = $1 AND status IN ('running', 'awaiting_decision')
`

func (q *Queries) GetLiveWorkflowStepRunForRun(ctx context.Context, workflowRunID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunForRun, workflowRunID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunningWorkflowRunForSession = `-- name: GetRunningWorkflowRunForSession :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at FROM workflow_runs WHERE session_id = $1 AND status = 'running'
`

func (q *Queries) GetRunningWorkflowRunForSession(ctx context.Context, sessionID pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getRunningWorkflowRunForSession, sessionID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getWorkflowBindingForRepo = `-- name: GetWorkflowBindingForRepo :one

SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name = $2
`

type GetWorkflowBindingForRepoParams struct {
	Lane         WorkflowLane `json:"lane"`
	RepoFullName *string      `json:"repo_full_name"`
}

// Queries backing WorkflowStore (Step 55, "workflow execution engine",
// §25.6/§25.7/§25.8), the first real reader/writer of Step 54's own dark
// schema (migrations/000057_workflows.up.sql). internal/app/workflowengine
// is this file's only caller: it resolves which (lane, repo) binding and
// WorkflowDefinition govern a session's current turn, tracks the run/
// step-run ledger these queries persist, and consults
// internal/domain/workflow.NextStep on every posted/derived step outcome
// -- never reimplementing that decision here.
//
// Binding resolution (§25.4): a repo-specific row (GetWorkflowBindingForRepo)
// always wins when one exists; GetGlobalWorkflowBinding is the guaranteed
// fallback (seeded by migration 000057 for every lane, so this SELECT is
// never truly expected to return zero rows in a correctly-migrated
// database -- see workflowengine's own fail-open handling for the
// defensive case where it somehow does).
//
// Definition assembly (GetWorkflowDefinition + ListWorkflowStepDefinitions +
// ListWorkflowEdgesForDefinition): three queries, not one join, mirroring
// domain/workflow.Definition's own shape (a definition row plus its
// ordered steps, each carrying its own outgoing edges) -- workflowengine
// groups edges by from_step_id in Go when assembling the domain value, the
// same "read plain rows, assemble the domain type in the app layer" split
// every other store in this package already follows (e.g. PlanStore never
// constructs an internal/domain/plan value itself).
//
// Run/step-run lifecycle (§25.6, migration 000057's own header comment):
// GetRunningWorkflowRunForSession/GetLiveWorkflowStepRunForRun back the
// "is there already a live run/step for this session" check
// ResolveStepForNewTurn makes before ever starting a new run --
// workflow_runs_one_running_per_session/workflow_step_runs_one_live_per_run
// (migration 000057) make violating either a live constraint violation,
// not just an application bug; this store's own CreateWorkflowRun/
// CreateWorkflowStepRun are therefore only ever called from the branch that
// already confirmed no live one exists. AttachTurnToWorkflowStepRun
// backfills turn_id once the actual turn row exists (it cannot exist before
// the step-run row is created, since ResolveStepForNewTurn must decide the
// step BEFORE the turn insert it feeds prompt/model into) --
// GetLiveWorkflowStepRunByTurnID is completion.go's own reverse lookup, at
// turn-completion time.
//
// MarkWorkflowStepRunAwaitingDecision/FinishWorkflowStepRun/
// CompleteWorkflowRun/EscalateWorkflowRun are deliberately four narrow,
// single-purpose statements rather than one CASE-parameterized UPDATE each
// -- mirroring plans.sql's own ApprovePlanIfAwaitingApproval/
// RejectPlanIfAwaitingApproval precedent (two verdicts, two statements) --
// so finished_at's own "null while awaiting_decision" invariant
// (migration 000057's own doc comment) is enforced by which statement runs,
// never by a conditional expression a future edit could silently get wrong.
// outcome_status uses COALESCE in both step-run UPDATEs so an outcome
// ALREADY posted via the step-outcome tool (SetWorkflowStepRunOutcome
// below) is never clobbered by the engine's own implicit-from-trigger
// derivation at turn-completion time -- the posted value always wins.
//
// SetWorkflowStepRunOutcome is the generic step-outcome-posting tool's own
// write (§25.6's typed {status, summary, structuredPayload} handoff,
// structurally mirroring internal/domain/reviewpost's existing
// verdict-posting shape): guarded to "AND status = 'running'" so a caller
// can only ever post onto the attempt currently actually in flight, never
// an already-finished or awaiting-decision one -- :execrows lets the
// handler distinguish "posted" from "no live attempt to post onto" without
// a separate existence check.
func (q *Queries) GetWorkflowBindingForRepo(ctx context.Context, arg GetWorkflowBindingForRepoParams) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getWorkflowBindingForRepo, arg.Lane, arg.RepoFullName)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT id, lane, name, is_built_in, version, created_at, updated_at FROM workflow_definitions WHERE id = $1
`

func (q *Queries) GetWorkflowDefinition(ctx context.Context, id pgtype.UUID) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, id)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listWorkflowEdgesForDefinition = `-- name: ListWorkflowEdgesForDefinition :many
SELECT id, workflow_definition_id, from_step_id, to_step_id, on_status, created_at FROM workflow_edges WHERE workflow_definition_id = $1
`

func (q *Queries) ListWorkflowEdgesForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, listWorkflowEdgesForDefinition, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEdge
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.FromStepID,
			&i.ToStepID,
			&i.OnStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepDefinitions = `-- name: ListWorkflowStepDefinitions :many
SELECT id, workflow_definition_id, step_order, kind, model_id, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position, created_at, updated_at FROM workflow_step_definitions WHERE workflow_definition_id = $1 ORDER BY step_order
`

func (q *Queries) ListWorkflowStepDefinitions(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowStepDefinition, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepDefinitions, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepDefinition
	for rows.Next() {
		var i WorkflowStepDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.StepOrder,
			&i.Kind,
			&i.ModelID,
			&i.PromptTemplate,
			&i.ExecutionScope,
			&i.ConversationContinuity,
			&i.HitlBefore,
			&i.HitlAfter,
			&i.CanvasPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowStepRunAwaitingDecision = `-- name: MarkWorkflowStepRunAwaitingDecision :one
UPDATE workflow_step_runs
SET status = 'awaiting_decision', outcome_status = COALESCE(outcome_status, $2), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type MarkWorkflowStepRunAwaitingDecisionParams struct {
	ID            pgtype.UUID                `json:"id"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

func (q *Queries) MarkWorkflowStepRunAwaitingDecision(ctx context.Context, arg MarkWorkflowStepRunAwaitingDecisionParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, markWorkflowStepRunAwaitingDecision, arg.ID, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setWorkflowStepRunOutcome = `-- name: SetWorkflowStepRunOutcome :execrows
UPDATE workflow_step_runs
SET outcome_status = $2, outcome_summary = $3, outcome_payload = $4, updated_at = now()
WHERE id = $1 AND status = 'running'
`

type SetWorkflowStepRunOutcomeParams struct {
	ID             pgtype.UUID                `json:"id"`
	OutcomeStatus  *WorkflowStepOutcomeStatus `json:"outcome_status"`
	OutcomeSummary *string                    `json:"outcome_summary"`
	OutcomePayload []byte                     `json:"outcome_payload"`
}

func (q *Queries) SetWorkflowStepRunOutcome(ctx context.Context, arg SetWorkflowStepRunOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkflowStepRunOutcome,
		arg.ID,
		arg.OutcomeStatus,
		arg.OutcomeSummary,
		arg.OutcomePayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
