// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ws_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWSToken = `-- name: CreateWSToken :one

INSERT INTO ws_tokens (session_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, user_id, token_hash, expires_at, created_at
`

type CreateWSTokenParams struct {
	SessionID pgtype.UUID        `json:"session_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing WSTokenStore (§4.3, §6.2's ws-token mint/verify
// mechanism, migrations/000016_ws_tokens.up.sql). CreateWSToken mints a
// fresh row -- the plaintext token itself, and hashing it, are the
// caller's own job (internal/platform.GenerateToken / HashToken), this
// query only ever sees the already-hashed value. GetWSTokenByHash is the
// client hub's own verify-by-hash lookup at subscribe time (§6.2).
// DeleteExpiredWSTokens backs RunExpiredTokenCleanup's own periodic sweep
// (expiredcleanup.go, audit-remediation config/platform-hardening batch):
// expires_at is otherwise only ever checked at read/verify time, so
// nothing else ever purges a row past its own TTL.
func (q *Queries) CreateWSToken(ctx context.Context, arg CreateWSTokenParams) (WsToken, error) {
	row := q.db.QueryRow(ctx, createWSToken,
		arg.SessionID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i WsToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredWSTokens = `-- name: DeleteExpiredWSTokens :execrows
DELETE FROM ws_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredWSTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredWSTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWSTokenByHash = `-- name: GetWSTokenByHash :one
SELECT id, session_id, user_id, token_hash, expires_at, created_at FROM ws_tokens
WHERE token_hash = $1
`

func (q *Queries) GetWSTokenByHash(ctx context.Context, tokenHash string) (WsToken, error) {
	row := q.db.QueryRow(ctx, getWSTokenByHash, tokenHash)
	var i WsToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
