package gitclone

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// agentsManifestFilename is the fixed name §6.4 pins for the generated
// manifest ("generated AGENTS.md manifest").
const agentsManifestFilename = "AGENTS.md"

// WriteAgentsManifest writes workspaceDir/AGENTS.md, a plain markdown
// manifest listing every SUCCESSFULLY cloned repo from results (any
// CloneResult with a non-nil Err is skipped entirely) -- name, path
// (workspaceDir/<name>), branch ("(default)" when Repo.Branch is nil), and
// primary/secondary.
//
// This exact markdown shape is this Step's own invented, documented
// convention: no contracts/ schema governs it, exactly like Step 14
// documented its own invented Readiness.Health shape. A later Step is free
// to change the rendering without needing to touch any wire contract.
//
// degradeNotes (Step 72, §27.1, adversarial-review LOW fix) is zero or
// more human-readable notes about a boot-time feature that degraded via
// the "warn and continue" policy (§27.1's own explicit words: a fetch
// failure is "recorded in the boot log and AGENTS.md, never a boot
// failure") -- e.g. a sandbox_secrets fetch that exhausted every retry
// attempt. §27.1's own stated RATIONALE for warn-and-continue being an
// acceptable degrade policy at all is exactly this: "a running agent that
// can diagnose a missing env var beats a dead sandbox" -- which only
// holds if the agent actually CAN diagnose it, i.e. this manifest (the
// one document AGENTS.md-reading tooling/agents are guaranteed to see)
// says so plainly, rather than leaving the agent to silently misbehave as
// if a normally-injected mechanism simply never existed. nil/empty (the
// overwhelming common case: every boot-time fetch succeeded, or this
// session has none of Step 72's own fetches to begin with) omits this
// section entirely -- this is an ADDITIVE section, never a replacement
// for the repo table above.
func WriteAgentsManifest(workspaceDir string, results []CloneResult, degradeNotes []string) error {
	var b strings.Builder

	b.WriteString("# AGENTS.md\n\n")
	b.WriteString("Generated by sandbox-agent at boot time (§6.4). Lists every repo cloned\n")
	b.WriteString("into this workspace for the current session.\n\n")
	b.WriteString("| Repo | Role | Path | Branch |\n")
	b.WriteString("| --- | --- | --- | --- |\n")

	for _, r := range results {
		if r.Err != nil {
			continue
		}

		role := "secondary"
		if r.Primary {
			role = "primary"
		}

		branch := "(default)"
		if r.Repo.Branch != nil {
			branch = *r.Repo.Branch
		}

		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Repo.Name, role, r.Dir, branch)
	}

	if len(degradeNotes) > 0 {
		b.WriteString("\n## Boot-time degrade notices\n\n")
		b.WriteString("The following boot-time features could not be fully applied for this\n")
		b.WriteString("session (warn-and-continue degrade policy, §27.1 -- never a boot\n")
		b.WriteString("failure). This agent is running WITHOUT them; diagnose accordingly\n")
		b.WriteString("rather than assuming they are simply unconfigured:\n\n")
		for _, note := range degradeNotes {
			fmt.Fprintf(&b, "- %s\n", note)
		}
	}

	path := filepath.Join(workspaceDir, agentsManifestFilename)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("gitclone: write %s: %w", path, err)
	}
	return nil
}
