package gitclone

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// agentsManifestFilename is the fixed name §6.4 pins for the generated
// manifest ("generated AGENTS.md manifest").
const agentsManifestFilename = "AGENTS.md"

// WriteAgentsManifest writes workspaceDir/AGENTS.md, a plain markdown
// manifest listing every SUCCESSFULLY cloned repo from results (any
// CloneResult with a non-nil Err is skipped entirely) -- name, path
// (workspaceDir/<name>), branch ("(default)" when Repo.Branch is nil), and
// primary/secondary.
//
// This exact markdown shape is this Step's own invented, documented
// convention: no contracts/ schema governs it, exactly like Step 14
// documented its own invented Readiness.Health shape. A later Step is free
// to change the rendering without needing to touch any wire contract.
func WriteAgentsManifest(workspaceDir string, results []CloneResult) error {
	var b strings.Builder

	b.WriteString("# AGENTS.md\n\n")
	b.WriteString("Generated by sandbox-agent at boot time (§6.4). Lists every repo cloned\n")
	b.WriteString("into this workspace for the current session.\n\n")
	b.WriteString("| Repo | Role | Path | Branch |\n")
	b.WriteString("| --- | --- | --- | --- |\n")

	for _, r := range results {
		if r.Err != nil {
			continue
		}

		role := "secondary"
		if r.Primary {
			role = "primary"
		}

		branch := "(default)"
		if r.Repo.Branch != nil {
			branch = *r.Repo.Branch
		}

		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", r.Repo.Name, role, r.Dir, branch)
	}

	path := filepath.Join(workspaceDir, agentsManifestFilename)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("gitclone: write %s: %w", path, err)
	}
	return nil
}
