package rwx

import "fmt"

// This file holds the shapes this adapter generates for / expects from the
// pinned `rwx` CLI's `--format json` sandbox-lifecycle surface. As doc.go
// explains, there is no real `rwx` CLI reachable from this codebase --
// these shapes are this adapter's own invention, pinned by the tests in
// provider_test.go against a fake cliRunner, NOT against a real pinned
// binary's own output.

// sandboxIdentityPath derives the deterministic per-(session, gen)
// identity string this adapter passes to the CLI as `--config` (§4.1.1:
// "generate a per-(session, gen) sandbox config whose... identity — RWX
// keys sandboxes on branch + config path — embeds session id AND gen, so
// two gens can never collide onto one RWX sandbox"). RWX itself keys a
// sandbox on branch + the absolute path to its config file (§4.1.1,
// quoting RWX's own docs) — this adapter therefore makes that path carry
// both values directly, rather than inventing a separate "sandbox name"
// concept RWX's own identity model has no place for.
//
// This same string becomes SandboxRef.ProviderID (ports/refs.go: "opaque
// outside the adapter") — StopSandbox passes it straight back as
// `--config`, needing no separate lookup or CLI-reported id: RWX's own
// identity model (branch + config path, not a server-assigned opaque id)
// means this adapter never needs to parse an id out of `sandbox start`'s
// own success output at all, unlike modal.Provider.CreateSandbox, which
// must parse Modal's own server-assigned sandboxId from its JSON response.
//
// Where the referenced config file itself is expected to live relative to
// a checked-out repo, and how it actually reaches RWX's own infrastructure
// for a horizontally-scaled, stateless control plane with no durable local
// checkout of its own, is NOT resolved here — an honestly-named gap
// alongside §4.1.3's own list, not a silently-assumed detail: §4.1.2 point
// 4 already establishes the precedent that a repo's own `.rwx` run
// definition is owned by the repo, not generated by Narvi's control plane;
// this adapter's own sandbox config is assumed to follow the same
// convention (checked into the session's repo at a well-known path this
// function's own output names), never authored ad hoc by this Go code.
func sandboxIdentityPath(sessionID string, gen int) string {
	return fmt.Sprintf("narvi/%s/gen-%d/sandbox.json", sessionID, gen)
}

// cliListEntry is one element of `rwx sandbox list --format json`'s own
// output array — RWX's own reconciliation/GC surface (§4.1: "List... for
// reconciliation/GC"). Config is whatever the CLI itself reports as this
// sandbox's own identity (the same branch+config-path shape
// sandboxIdentityPath derives when THIS adapter is the one creating a
// sandbox) — parsed opaquely into SandboxRef.ProviderID, never assumed to
// match sandboxIdentityPath's own generated format for a sandbox this
// process did not itself create (e.g. one another pod's Provider created,
// or one a human created directly via the CLI).
type cliListEntry struct {
	Config string `json:"config"`
}
