package githubapi_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/khazaddev/narvi/internal/adapters/outbound/githubapi"
	"github.com/khazaddev/narvi/internal/app/ports"
)

// TestCreatePR_Success proves CreatePR posts the right shape to
// /repos/{owner}/{repo}/pulls and parses a real GitHub-shaped success
// response.
func TestCreatePR_Success(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth, gotAccept string
	var gotBody map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		if err := json.NewDecoder(r.Body).Decode(&gotBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number":   42,
			"html_url": "https://github.com/acme/widgets/pull/42",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	ref, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Body:  "Generated by narvi.",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil", err)
	}

	if gotPath != "/repos/acme/widgets/pulls" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/pulls")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
	if gotAccept != "application/vnd.github+json" {
		t.Errorf("Accept header = %q, want %q", gotAccept, "application/vnd.github+json")
	}
	if gotBody["title"] != "Narvi: do the thing" || gotBody["head"] != "narvi/session-123" || gotBody["base"] != "main" {
		t.Errorf("request body = %+v, missing expected fields", gotBody)
	}

	if ref.Number != 42 {
		t.Errorf("PRRef.Number = %d, want 42", ref.Number)
	}
	if ref.URL != "https://github.com/acme/widgets/pull/42" {
		t.Errorf("PRRef.URL = %q, want %q", ref.URL, "https://github.com/acme/widgets/pull/42")
	}
}

// TestCreatePR_4xxMapsToRealError proves a realistic GitHub 4xx failure
// (e.g. a validation error on an already-existing PR) maps to a real,
// structured *githubapi.CreatePRError, never a panic or a silently-empty
// PRRef mistaken for success.
func TestCreatePR_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"message": "A pull request already exists for acme:narvi/session-123.",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("CreatePR() error = nil, want a *githubapi.CreatePRError")
	}

	var prErr *githubapi.CreatePRError
	if !asCreatePRError(err, &prErr) {
		t.Fatalf("CreatePR() error = %v (%T), want *githubapi.CreatePRError", err, err)
	}
	if prErr.Status != http.StatusUnprocessableEntity {
		t.Errorf("CreatePRError.Status = %d, want %d", prErr.Status, http.StatusUnprocessableEntity)
	}
	if prErr.Message == "" {
		t.Error("CreatePRError.Message is empty, want GitHub's own error message")
	}
}

// TestNew_DefaultsAPIBaseURL proves an empty apiBaseURL falls back to
// GitHub's own real API host rather than an empty/unusable base.
func TestNew_DefaultsAPIBaseURL(t *testing.T) {
	t.Parallel()

	adapter := githubapi.New(nil, "")
	if adapter == nil {
		t.Fatal("New(nil, \"\") = nil, want a non-nil *Adapter")
	}
}

func asCreatePRError(err error, target **githubapi.CreatePRError) bool {
	pe, ok := err.(*githubapi.CreatePRError)
	if !ok {
		return false
	}
	*target = pe
	return true
}
