package githubapi_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"

	"github.com/khazaddev/narvi/internal/adapters/outbound/githubapi"
	"github.com/khazaddev/narvi/internal/app/ports"
	"github.com/khazaddev/narvi/internal/domain/contractdrift"
)

// TestCreatePR_Success proves CreatePR posts the right shape to
// /repos/{owner}/{repo}/pulls and parses a real GitHub-shaped success
// response.
func TestCreatePR_Success(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth, gotAccept string
	var gotBody map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		if err := json.NewDecoder(r.Body).Decode(&gotBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number":   42,
			"html_url": "https://github.com/acme/widgets/pull/42",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	ref, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Body:  "Generated by narvi.",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil", err)
	}

	if gotPath != "/repos/acme/widgets/pulls" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/pulls")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
	if gotAccept != "application/vnd.github+json" {
		t.Errorf("Accept header = %q, want %q", gotAccept, "application/vnd.github+json")
	}
	if gotBody["title"] != "Narvi: do the thing" || gotBody["head"] != "narvi/session-123" || gotBody["base"] != "main" {
		t.Errorf("request body = %+v, missing expected fields", gotBody)
	}

	if ref.Number != 42 {
		t.Errorf("PRRef.Number = %d, want 42", ref.Number)
	}
	if ref.URL != "https://github.com/acme/widgets/pull/42" {
		t.Errorf("PRRef.URL = %q, want %q", ref.URL, "https://github.com/acme/widgets/pull/42")
	}
}

// TestCreatePR_4xxMapsToRealError proves a realistic GitHub 4xx failure
// (e.g. a validation error on an already-existing PR) maps to a real,
// structured *githubapi.CreatePRError, never a panic or a silently-empty
// PRRef mistaken for success.
func TestCreatePR_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"message": "A pull request already exists for acme:narvi/session-123.",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("CreatePR() error = nil, want a *githubapi.CreatePRError")
	}

	var prErr *githubapi.CreatePRError
	if !asCreatePRError(err, &prErr) {
		t.Fatalf("CreatePR() error = %v (%T), want *githubapi.CreatePRError", err, err)
	}
	if prErr.Status != http.StatusUnprocessableEntity {
		t.Errorf("CreatePRError.Status = %d, want %d", prErr.Status, http.StatusUnprocessableEntity)
	}
	if prErr.Message == "" {
		t.Error("CreatePRError.Message is empty, want GitHub's own error message")
	}
}

// --- URL escaping (audit remediation: security-crosscutting lens) ---
//
// Each test below asserts against the real *http.Request.URL the server
// actually received (via r.URL.EscapedPath(), the exact wire-encoded path,
// and r.URL.Query(), the real parsed query values) -- not merely that the
// call returned no error -- so a regression that silently stopped escaping
// (e.g. reverting to a bare fmt.Sprintf) would fail these tests even
// though the fake server itself never rejects any request shape.

// TestCreatePR_EscapesOwnerAndRepo proves a malicious Owner/Repo containing
// a "/" and a "#" cannot inject an extra path segment or truncate the
// request via an unintended URL fragment.
func TestCreatePR_EscapesOwnerAndRepo(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{"number": 1, "html_url": "https://github.com/x/y/pull/1"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme/evil",
		Repo:  "widgets#v1",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "t",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1/pulls"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo must be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestResolveBranchSHA_EscapesOwnerRepoAndBranch proves a malicious
// Owner/Repo/Branch is escaped on BOTH request paths ResolveBranchSHA can
// build: the repo-info lookup (only reached when Branch is empty) and the
// commits lookup, whose OWN ref segment is the resolved default_branch
// value in this path -- itself attacker-shaped here, since a real GitHub
// default_branch is caller-controlled from ResolveBranchSHA's own point of
// view.
func TestResolveBranchSHA_EscapesOwnerRepoAndBranch(t *testing.T) {
	t.Parallel()

	var gotEscapedPaths []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPaths = append(gotEscapedPaths, r.URL.EscapedPath())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		switch {
		case len(gotEscapedPaths) == 1:
			_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "release/1.0#x"})
		default:
			_ = json.NewEncoder(w).Encode(map[string]any{"sha": "abc123"})
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, _, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner: "acme/evil",
		Repo:  "widgets#v1",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "abc123" {
		t.Errorf("ResolveBranchSHA() = %q, want %q", sha, "abc123")
	}

	if len(gotEscapedPaths) != 2 {
		t.Fatalf("server received %d requests, want 2", len(gotEscapedPaths))
	}
	wantRepoPath := "/repos/acme%2Fevil/widgets%23v1"
	if gotEscapedPaths[0] != wantRepoPath {
		t.Errorf("repo-info request EscapedPath = %q, want %q", gotEscapedPaths[0], wantRepoPath)
	}
	// branch (the resolved default_branch "release/1.0#x") is escaped as a
	// single opaque path segment -- GitHub's own commits/{ref} endpoint
	// requires a "/" WITHIN a ref to be percent-encoded (%2F) to
	// disambiguate it from a route-segment boundary, exactly what
	// url.PathEscape produces here.
	wantCommitPath := "/repos/acme%2Fevil/widgets%23v1/commits/release%2F1.0%23x"
	if gotEscapedPaths[1] != wantCommitPath {
		t.Errorf("commit request EscapedPath = %q, want %q", gotEscapedPaths[1], wantCommitPath)
	}
}

// TestResolveContractsFingerprint_EscapesOwnerRepoPathAndRef proves the
// sharpest case the audit named: a spec.Path containing "?ref=attacker&"
// must not rewrite the request's real query string (the actual spec.Ref
// must still win), and a spec.Path containing "#" must not truncate the
// request via an unintended URL fragment -- while a real, multi-segment
// spec.Path (containing legitimate "/" directory separators) must still
// resolve to a real, correctly nested GitHub Contents API path, not a
// single mangled segment.
func TestResolveContractsFingerprint_EscapesOwnerRepoPathAndRef(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name            string
		path            string
		ref             string
		wantEscapedTail string
		wantRefQuery    string
	}{
		{
			name:            "query-injection attempt via path is neutralized",
			path:            "x?ref=attacker&",
			ref:             "realref",
			wantEscapedTail: "/contents/x%3Fref=attacker&",
			wantRefQuery:    "realref",
		},
		{
			name:            "fragment-truncation attempt via path is neutralized",
			path:            "x#evilfragment",
			ref:             "realref",
			wantEscapedTail: "/contents/x%23evilfragment",
			wantRefQuery:    "realref",
		},
		{
			name:            "a real multi-segment path still resolves as nested directories",
			path:            "services/mock-api/contracts",
			ref:             "abc123",
			wantEscapedTail: "/contents/services/mock-api/contracts",
			wantRefQuery:    "abc123",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			var gotEscapedPath string
			var gotQuery url.Values
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				gotEscapedPath = r.URL.EscapedPath()
				gotQuery = r.URL.Query()
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_ = json.NewEncoder(w).Encode([]map[string]any{})
			}))
			defer server.Close()

			adapter := githubapi.New(server.Client(), server.URL)

			_, _, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
				Owner: "acme",
				Repo:  "widgets",
				Ref:   tc.ref,
				Path:  tc.path,
				Token: "gho_realtoken",
			})
			if err != nil {
				t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
			}

			wantEscapedPath := "/repos/acme/widgets" + tc.wantEscapedTail
			if gotEscapedPath != wantEscapedPath {
				t.Errorf("request EscapedPath = %q, want %q", gotEscapedPath, wantEscapedPath)
			}
			// len == 1 proves the malicious path never smuggled in a SECOND
			// query key/value the attacker controlled (e.g. its own "ref").
			if len(gotQuery["ref"]) != 1 || gotQuery.Get("ref") != tc.wantRefQuery {
				t.Errorf("request query ref = %v, want exactly one value %q", gotQuery["ref"], tc.wantRefQuery)
			}
		})
	}
}

// TestNew_DefaultsAPIBaseURL proves an empty apiBaseURL falls back to
// GitHub's own real API host rather than an empty/unusable base.
func TestNew_DefaultsAPIBaseURL(t *testing.T) {
	t.Parallel()

	adapter := githubapi.New(nil, "")
	if adapter == nil {
		t.Fatal("New(nil, \"\") = nil, want a non-nil *Adapter")
	}
}

func asCreatePRError(err error, target **githubapi.CreatePRError) bool {
	pe, ok := err.(*githubapi.CreatePRError)
	if !ok {
		return false
	}
	*target = pe
	return true
}

// TestResolveBranchSHA_ExplicitBranch proves an explicit branch resolves
// directly via GET /repos/{owner}/{repo}/commits/{branch}, with NO call to
// the repo-info endpoint at all (the default-branch lookup is only ever
// needed when Branch is empty).
func TestResolveBranchSHA_ExplicitBranch(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{"sha": "abc123def456"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, resolvedBranch, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner:  "acme",
		Repo:   "widgets",
		Branch: "feature-x",
		Token:  "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "abc123def456" {
		t.Errorf("ResolveBranchSHA() sha = %q, want %q", sha, "abc123def456")
	}
	if resolvedBranch != "feature-x" {
		t.Errorf("ResolveBranchSHA() resolvedBranch = %q, want %q (explicit branch echoed back verbatim)", resolvedBranch, "feature-x")
	}
	if gotPath != "/repos/acme/widgets/commits/feature-x" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/commits/feature-x")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
}

// TestResolveBranchSHA_EmptyBranchResolvesDefault proves an empty Branch
// first resolves the repo's own REAL default_branch (never a hardcoded
// "main"/"master" guess), then resolves THAT branch's commit SHA.
func TestResolveBranchSHA_EmptyBranchResolvesDefault(t *testing.T) {
	t.Parallel()

	var gotPaths []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPaths = append(gotPaths, r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		switch r.URL.Path {
		case "/repos/acme/widgets":
			_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "trunk"})
		case "/repos/acme/widgets/commits/trunk":
			_ = json.NewEncoder(w).Encode(map[string]any{"sha": "def789"})
		default:
			t.Errorf("unexpected request path %q", r.URL.Path)
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, resolvedBranch, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "def789" {
		t.Errorf("ResolveBranchSHA() sha = %q, want %q", sha, "def789")
	}
	if resolvedBranch != "trunk" {
		t.Errorf("ResolveBranchSHA() resolvedBranch = %q, want %q (the repo's own real default branch, not left empty)", resolvedBranch, "trunk")
	}
	wantPaths := []string{"/repos/acme/widgets", "/repos/acme/widgets/commits/trunk"}
	if len(gotPaths) != len(wantPaths) || gotPaths[0] != wantPaths[0] || gotPaths[1] != wantPaths[1] {
		t.Errorf("requested paths = %v, want %v (in order)", gotPaths, wantPaths)
	}
}

// TestResolveBranchSHA_4xxMapsToRealError proves a realistic GitHub 4xx
// failure (e.g. repo not found / no access) maps to a real, structured
// *githubapi.APIError, never a panic or a silently-empty SHA mistaken for
// success.
func TestResolveBranchSHA_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner:  "acme",
		Repo:   "widgets",
		Branch: "main",
		Token:  "gho_realtoken",
	})
	if err == nil {
		t.Fatal("ResolveBranchSHA() error = nil, want a *githubapi.APIError")
	}

	var shaErr *githubapi.APIError
	if !errors.As(err, &shaErr) {
		t.Fatalf("ResolveBranchSHA() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if shaErr.Status != http.StatusNotFound {
		t.Errorf("APIError.Status = %d, want %d", shaErr.Status, http.StatusNotFound)
	}
	if shaErr.Message == "" {
		t.Error("APIError.Message is empty, want GitHub's own error message")
	}
}

// TestResolveContractsFingerprint_DirectoryExists proves a real contents
// listing (several files) fingerprints to EXACTLY contractdrift.
// Fingerprint's own output over the identical path->sha map -- proving
// this adapter builds that map correctly, not re-implementing its own
// hashing.
func TestResolveContractsFingerprint_DirectoryExists(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path + "?" + r.URL.RawQuery
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"path": "contracts/api/openapi.yaml", "sha": "sha-openapi", "type": "file"},
			{"path": "contracts/api/README.md", "sha": "sha-readme", "type": "file"},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
	}
	if !exists {
		t.Fatal("ResolveContractsFingerprint() exists = false, want true")
	}

	want := contractdrift.Fingerprint(map[string]string{
		"contracts/api/openapi.yaml": "sha-openapi",
		"contracts/api/README.md":    "sha-readme",
	})
	if fingerprint != want {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want %q", fingerprint, want)
	}

	if gotPath != "/repos/acme/widgets/contents/contracts/api?ref=abc123" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/contents/contracts/api?ref=abc123")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
}

// TestResolveContractsFingerprint_404_ExistsFalseNoError proves a 404 (no
// contracts directory at that path/ref -- the common case) maps to
// (exists=false, err=nil), never a real error -- per ports.SourceControl's
// own doc comment, callers MUST be able to tell this apart from a genuine
// API failure.
func TestResolveContractsFingerprint_404_ExistsFalseNoError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil on a 404", err)
	}
	if exists {
		t.Error("ResolveContractsFingerprint() exists = true, want false on a 404")
	}
	if fingerprint != "" {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want empty on a 404", fingerprint)
	}
}

// TestResolveContractsFingerprint_NonNotFoundErrorPropagates proves a
// non-404 failure (e.g. a real 500, or no access at all) is a genuine
// error -- exists=false AND err != nil, never silently treated the same
// as "no directory here".
func TestResolveContractsFingerprint_NonNotFoundErrorPropagates(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Internal Server Error"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("ResolveContractsFingerprint() error = nil, want a real error on a 500")
	}
	if exists {
		t.Error("ResolveContractsFingerprint() exists = true, want false on a real error")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("ResolveContractsFingerprint() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusInternalServerError {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusInternalServerError)
	}
}

// TestResolveContractsFingerprint_NestedSubdirectoryNotRecursedInto proves
// a listing containing a nested subdirectory entry is fingerprinted using
// THAT entry's own sha as-is -- never recursed into -- by asserting the
// server sees exactly ONE request even though the fake listing includes a
// "dir"-typed entry, and that the resulting fingerprint matches
// contractdrift.Fingerprint's own direct computation over the identical
// flat map (which itself never recurses either).
func TestResolveContractsFingerprint_NestedSubdirectoryNotRecursedInto(t *testing.T) {
	t.Parallel()

	var requestCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		requestCount++
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"path": "contracts/api/openapi.yaml", "sha": "sha-openapi", "type": "file"},
			{"path": "contracts/api/schemas", "sha": "sha-subdir-tree-hash", "type": "dir"},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
	}
	if !exists {
		t.Fatal("ResolveContractsFingerprint() exists = false, want true")
	}

	if requestCount != 1 {
		t.Errorf("server received %d requests, want exactly 1 (no recursion into the subdirectory entry)", requestCount)
	}

	want := contractdrift.Fingerprint(map[string]string{
		"contracts/api/openapi.yaml": "sha-openapi",
		"contracts/api/schemas":      "sha-subdir-tree-hash",
	})
	if fingerprint != want {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want %q (the subdirectory's own sha used as-is)", fingerprint, want)
	}
}
