// §12.1's own SPA-no-SSR-no-BFF architecture, wired up here: Vite builds a
// static bundle (`npm run build`), which cmd/control-plane embeds via
// go:embed and serves on the SAME port as the REST/WS API (see
// internal/adapters/inbound/webui's own doc comment for the embed side).
// No dev-server proxy to a Go backend is configured here yet -- that lands
// with the real data layer (§12.1's "WS transport -> event log -> reducer"),
// not this bootstrap.
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { tanstackRouter } from '@tanstack/router-plugin/vite'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const here = path.dirname(fileURLToPath(import.meta.url))

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    // Must run BEFORE @vitejs/plugin-react (TanStack Router's own documented
    // ordering requirement): it rewrites src/routes/**/*.tsx into route
    // definitions and regenerates src/routeTree.gen.ts (gitignored --
    // regenerated by this plugin on every `vite dev`/`vite build`, so a
    // fresh checkout never needs it committed) before the React transform
    // sees the resulting JSX.
    tanstackRouter({ target: 'react', autoCodeSplitting: true }),
    react(),
  ],
  resolve: {
    alias: {
      // §12.1's data layer ("no hand-written response types anywhere"):
      // every generated file under contracts/gen/ts/ is exposed to web/src
      // under this one stable specifier rather than a relative path whose
      // "../" count depends on how deep the importing file happens to
      // live (and breaks silently -- wrong file, not a compile error -- if
      // that file ever moves). contracts/ is its own separate npm project
      // (@narvi/contracts, contracts/package.json's own description: "does
      // not make the repo root an npm project; phase 6 brings its own
      // frontend package"), not an npm workspace dependency of web/, so
      // this alias, mirrored in tsconfig.app.json's own "paths" (for
      // tsc -b) and vitest.config.ts (for tests), is what actually wires
      // the two projects together. See web/README.md's own "Generated
      // contracts" section for the full "why an alias, not a relative
      // path or a workspace dependency" writeup.
      '@narvi/contracts': path.resolve(here, '../contracts/gen/ts'),
    },
  },
  build: {
    // Points DIRECTLY at internal/adapters/inbound/webui/dist -- the exact
    // directory that package's own `//go:embed all:dist` directive (see
    // assets_embed.go) reads from -- rather than the more conventional
    // web/dist. This is not a stylistic choice: go:embed's own directive
    // syntax forbids a pattern that walks outside the Go package's own
    // directory (no `..` allowed at all), so the embed source cannot live
    // under web/ unless it is EITHER copied there as an extra build step,
    // or Vite is pointed at it directly. Pointing Vite here needs no
    // separate copy/sync step, and no second on-disk copy of the build to
    // ever drift out of sync with the one go:embed actually reads.
    outDir: path.resolve(here, '../internal/adapters/inbound/webui/dist'),
    // Required whenever outDir resolves outside Vite's own project root
    // (here, web/) -- Vite refuses to silently empty a directory it does
    // not consider "its own" otherwise, as a safety rail against wiping
    // something unrelated.
    emptyOutDir: true,
  },
})
